<a href="https://colab.research.google.com/github/Peckkie/Experiment_Evaluation_CCA/blob/main/Checking_Result_ExpRadio_Wrong.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# คำสั่ง  drive.mount : เป็นผูก google drive กับ colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
os.chdir( '/content/drive/MyDrive/CCA_Project')
!pwd

/content/drive/MyDrive/CCA_Project

In [3]:
import pandas as pd
df = pd.read_csv( '/content/drive/MyDrive/CCA_Project/result_csv/Experiment2_AI.csv')
df.head(3)

   Unnamed: 0  num            FileName  ... B10_Pred2_ass B11_Pred2 B12_Pred2
0           0    1    AB01 P1 C100.JPG  ...          AB02      AB02      AB01
1           1    2  AB01 P4-2 C050.JPG  ...          AB02      AB01    Normal
2           2    3  AB01 P5-2 C004.JPG  ...          AB01      AB02    Normal

[3 rows x 45 columns]

In [6]:
df_ = df[['FileName','Path Full', 'B10_Pred2_ass','B11_Pred1_ass','B12_Pred1_ass','U10_Pred2_ass','U11_Pred','U20_Pred_ass','U21_Pred2_ass','U30_Pred2_ass','U31_Pred_ass','U40_Pred_ass','U41_Pred2_ass','Sub_class_New','category']]
df_.head()

             FileName  ... category
0    AB01 P1 C100.JPG  ...     AB02
1  AB01 P4-2 C050.JPG  ...     AB02
2  AB01 P5-2 C004.JPG  ...     AB01
3    AB02 P1 C001.JPG  ...     AB02
4  AB02 P3-1 C001.JPG  ...     AB01

[5 rows x 15 columns]

In [8]:
per = ['B10_Pred2_ass','B11_Pred1_ass','B12_Pred1_ass','U10_Pred2_ass','U11_Pred','U20_Pred_ass','U21_Pred2_ass','U30_Pred2_ass','U31_Pred_ass','U40_Pred_ass','U41_Pred2_ass']

for i in per:
    act = df_['Sub_class_New'].tolist()
    per_= df_[i].tolist()

    a_ =[]
    for  j in range(len(per_)):
        if act[j]==per_[j]:
            a = 'Correct'
            a_.append(a)
        else:
            a = 'Incorrect'
            a_.append(a) 
    df_[i+'_']  = a_

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app

In [9]:
df_

               FileName  ... U41_Pred2_ass_
0      AB01 P1 C100.JPG  ...        Correct
1    AB01 P4-2 C050.JPG  ...      Incorrect
2    AB01 P5-2 C004.JPG  ...      Incorrect
3      AB02 P1 C001.JPG  ...        Correct
4    AB02 P3-1 C001.JPG  ...        Correct
..                  ...  ...            ...
145          P8C193.jpg  ...        Correct
146     P8_Case_007.jpg  ...        Correct
147     P8_Case_025.jpg  ...        Correct
148     P8_Case_029.jpg  ...        Correct
149     P8_Case_032.jpg  ...        Correct

[150 rows x 26 columns]

In [ ]:
max = df_['Dup_clas'].tolist()
act = df_['Sub_class_New'].tolist()
ai = df_['category'].tolist()

a_ =[]
ai = df_['category'].tolist()
for  i in range(len(max)):
    if act[i]==max[i]:
        a = 'Correct'
        a_.append(a)
    else:
        a = 'Incorrect'
        a_.append(a) 
df_['Result_Act']  = a_