In [90]:
import pandas as pd
df = pd.read_csv( '/home/yupaporn/CCA_Project/result_BiTNet_DiagRadioExp_AzureDb813_modelFull.csv')#แก้
df

,Unnamed: 0,Unnamed: 0.1,0,1,2,3,4,5,6,7,...,P ID,date,Path crop,Class,Sub_class_name,Sub_class,category,Prob,category_BiTNet,Prob_BiTNet
0,0,0,0.162170,0.373119,-0.206777,-0.090784,-0.106962,0.170049,-0.154019,-0.031511,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.999286,Normal,0.253901
1,1,1,0.200935,-0.107537,-0.176930,-0.183966,-0.095405,0.093535,-0.144208,-0.010653,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.993507,Normal,0.201056
2,2,2,0.426072,0.070388,-0.102109,-0.159541,-0.189294,0.219006,-0.098589,0.136929,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.985898,AB05,0.122304
3,3,3,0.033356,-0.066455,-0.004623,-0.036767,-0.215879,0.243723,-0.112175,-0.170005,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.988357,Normal,0.253287
4,4,4,-0.057476,0.013760,-0.219840,-0.147638,-0.093520,0.209551,-0.175600,-0.201921,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.999318,Normal,0.222448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
808,808,808,-0.036016,-0.030781,-0.002133,-0.115271,-0.156255,0.060351,-0.150695,-0.181863,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],AB12,0.999449,AB12,0.146540
809,809,809,0.282880,0.054666,-0.187765,-0.020248,0.111334,0.130226,-0.186284,0.037036,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.872921
810,810,810,-0.017516,-0.033841,-0.151241,0.254034,0.219540,-0.003998,-0.181064,-0.068055,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.756502
811,811,811,-0.129069,-0.157385,0.074567,0.005774,-0.141309,0.228510,-0.196027,-0.195661,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],AB12,0.761010,AB12,0.214176
812,812,812,-0.132999,0.168370,-0.202881,-0.148894,-0.189075,-0.048664,-0.137881,-0.126959,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.996289,Normal,0.269860

# Abnormal

In [91]:
# abnormal = df[df['Class'] != 'Normal']
# abnormal.head()
abnormal = df

In [92]:
class_ = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']

col_name = ['Case', 'Act_label', 'Pred_label','Num_PredCase']
dff2 = pd.DataFrame(columns = col_name)

df_ = abnormal

case = list(set(df_['P ID']))
pred_label = []
num_case = []
act_label = []

for i in case:
    cas_pred = set(df_[df_['P ID'] == i]['category_BiTNet'])
    cas_act = list(df_[df_['P ID'] == i]['Sub_class'])
    pred_label.append(list(cas_pred))
    act_label.append(cas_act[0])
    num_case.append(len(cas_pred))

dff2['Pred_label'] = pred_label
dff2['Case'] = case
dff2['Num_PredCase'] = num_case
dff2['Act_label'] = act_label  

dff2

     Case          Act_label                         Pred_label  Num_PredCase
0    6668   ['AB02', 'AB11']                     [Normal, AB12]             2
1    6798         ['Normal']                     [Normal, AB12]             2
2    7725           ['AB01']                     [Normal, AB12]             2
3    6446           ['AB09']                     [Normal, AB12]             2
4   12215         ['Normal']                     [Normal, AB12]             2
5   12216         ['Normal']                     [Normal, AB12]             2
6   12217         ['Normal']         [Normal, AB03, AB01, AB12]             4
7   12218         ['Normal']                     [Normal, AB12]             2
8   12219         ['Normal']               [Normal, AB06, AB12]             3
9   12220         ['Normal']                     [Normal, AB12]             2
10  12221           ['AB01']                     [Normal, AB12]             2
11  12222           ['AB02']                     [Normal, AB12]             2
12  12285         ['Normal']                     [Normal, AB12]             2
13   6600           ['AB01']  [AB082, Normal, AB12, AB01, AB05]             5
14   6472  ['AB06', 'AB081']                     [Normal, AB12]             2
15  12279           ['AB09']                     [Normal, AB12]             2
16   7895           ['AB10']               [Normal, AB05, AB12]             3
17  12248         ['Normal']        [Normal, AB05, AB12, AB081]             4
18  12280         ['Normal']                     [Normal, AB12]             2
19   6621           ['AB01']                     [Normal, AB12]             2
20   6624           ['AB05']                     [Normal, AB12]             2
21  12282         ['Normal']               [Normal, AB05, AB12]             3
22  12259           ['AB01']                     [Normal, AB12]             2
23  12260         ['Normal']              [Normal, AB081, AB12]             3
24  12261           ['AB02']        [Normal, AB02, AB081, AB12]             4
25  12262         ['Normal']                     [Normal, AB12]             2
26  12263           ['AB11']                     [Normal, AB12]             2
27  12264           ['AB01']                     [Normal, AB12]             2
28  12265           ['AB03']         [Normal, AB03, AB02, AB12]             4
29  12266         ['Normal']                     [Normal, AB12]             2
30  12283         ['Normal']                     [Normal, AB12]             2
31  12284         ['Normal']               [Normal, AB03, AB12]             3
32  12269         ['Normal']                           [Normal]             1
33  12270         ['Normal']                     [Normal, AB12]             2
34  12271         ['Normal']                     [Normal, AB12]             2
35   6640           ['AB11']                     [Normal, AB12]             2
36  12273         ['Normal']                     [Normal, AB12]             2
37  12274         ['Normal']                     [Normal, AB12]             2
38  12275           ['AB01']               [Normal, AB02, AB12]             3
39  12276         ['Normal']               [Normal, AB05, AB12]             3
40  12277         ['Normal']                     [Normal, AB12]             2
41  12150         ['Normal']               [Normal, AB05, AB12]             3
42  12151         ['Normal']                     [Normal, AB12]             2
43  12152         ['Normal']                     [Normal, AB12]             2
44  12281         ['Normal']        [Normal, AB082, AB05, AB12]             4
45  12154         ['Normal']                     [Normal, AB12]             2
46  12155         ['Normal']              [Normal, AB12, AB081]             3
47  12156         ['Normal']                     [Normal, AB12]             2
48   6525         ['Normal']                     [Normal, AB12]             2
49  12158           ['AB01']                     [Normal, AB12]             2
50   7039           ['AB11']                     [Normal, AB12]             2

In [93]:
#แปลงข้อมูล

        
Act_label = dff2['Act_label'].tolist()
Act_label_ =[]
for i in Act_label:   
    a = i.split("'")
    if len(a) ==5:
        m = a[1],a[3]
        g =[]
        for j in range(2):
            g.append(m[j])
        Act_label_.append(g)
    else:
        g =[]
        g.append(a[1])
        Act_label_.append(g)
dff2['Act_label_'] = Act_label_

In [94]:
Act = dff2['Act_label_'].tolist()
class_ = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']
# class_ = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12']


cla_act = []
for i in Act:
    if len(list(i)) == 1:
#         print(list(i))
        a = str(list(i)[0])
        for j in range(len(class_)):
            if a == class_[j]:
                m = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
                m[j] = 1
                cla_act.append(m)
#                 print(m)
    else:
        m = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        for j in list(i):
#             print(list(i))
            for k in range(len(class_)):
                if j == class_[k]:
                    m[k] = 1
        cla_act.append(m)
#         print(m)

In [95]:
a =[]
for i in cla_act:
    a.append(i[0:14])
#     print(i[0:14])
cla_act_ = a

In [96]:
cla_act_

[[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]]

In [97]:
Pred = dff2['Pred_label'].tolist()
class_ = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']

cla_pred = []
for i in Pred:
    if len(list(i)) == 1:
        a = str(list(i)[0])
        for j in range(len(class_)):
            if a == class_[j]:
                m = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
                m[j] = 1
                cla_pred.append(m)
    else:
        m = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        for j in list(i):
#             print(list(i))
            for k in range(len(class_)):
                if j == class_[k]:
                    m[k] = 1
        cla_pred.append(m)
#         print(m)

In [98]:
a =[]
for i in cla_pred:
    a.append(i[0:14])
#     print(i[0:14])
cla_pred_ = a

In [99]:
cla_pred_

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
 [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]

In [100]:
dff2['Act'] = cla_act_
dff2['Pred'] = cla_pred_
dff2

,Case,Act_label,Pred_label,Num_PredCase,Act_label_,Act,Pred
0,6668,"['AB02', 'AB11']","[Normal, AB12]",2,"[AB02, AB11]","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
1,6798,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
2,7725,['AB01'],"[Normal, AB12]",2,[AB01],"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
3,6446,['AB09'],"[Normal, AB12]",2,[AB09],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
4,12215,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
5,12216,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
6,12217,['Normal'],"[Normal, AB03, AB01, AB12]",4,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
7,12218,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
8,12219,['Normal'],"[Normal, AB06, AB12]",3,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1]"
9,12220,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
10,12221,['AB01'],"[Normal, AB12]",2,[AB01],"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
11,12222,['AB02'],"[Normal, AB12]",2,[AB02],"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
12,12285,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
13,6600,['AB01'],"[AB082, Normal, AB12, AB01, AB05]",5,[AB01],"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1]"
14,6472,"['AB06', 'AB081']","[Normal, AB12]",2,"[AB06, AB081]","[0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
15,12279,['AB09'],"[Normal, AB12]",2,[AB09],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
16,7895,['AB10'],"[Normal, AB05, AB12]",3,[AB10],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
17,12248,['Normal'],"[Normal, AB05, AB12, AB081]",4,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1]"
18,12280,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
19,6621,['AB01'],"[Normal, AB12]",2,[AB01],"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
20,6624,['AB05'],"[Normal, AB12]",2,[AB05],"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
21,12282,['Normal'],"[Normal, AB05, AB12]",3,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
22,12259,['AB01'],"[Normal, AB12]",2,[AB01],"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
23,12260,['Normal'],"[Normal, AB081, AB12]",3,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1]"
24,12261,['AB02'],"[Normal, AB02, AB081, AB12]",4,[AB02],"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1]"
25,12262,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
26,12263,['AB11'],"[Normal, AB12]",2,[AB11],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
27,12264,['AB01'],"[Normal, AB12]",2,[AB01],"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
28,12265,['AB03'],"[Normal, AB03, AB02, AB12]",4,[AB03],"[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
29,12266,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
30,12283,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
31,12284,['Normal'],"[Normal, AB03, AB12]",3,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
32,12269,['Normal'],[Normal],1,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
33,12270,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
34,12271,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
35,6640,['AB11'],"[Normal, AB12]",2,[AB11],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
36,12273,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
37,12274,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
38,12275,['AB01'],"[Normal, AB02, AB12]",3,[AB01],"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
39,12276,['Normal'],"[Normal, AB05, AB12]",3,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
40,12277,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
41,12150,['Normal'],"[Normal, AB05, AB12]",3,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
42,12151,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
43,12152,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
44,12281,['Normal'],"[Normal, AB082, AB05, AB12]",4,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1]"
45,12154,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
46,12155,['Normal'],"[Normal, AB12, AB081]",3,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1]"
47,12156,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
48,6525,['Normal'],"[Normal, AB12]",2,[Normal],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
49,12158,['AB01'],"[Normal, AB12]",2,[AB01],"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
50,7039,['AB11'],"[Normal, AB12]",2,[AB11],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"

In [101]:
import numpy as np
y_true = np.array(cla_act_)
y_pred = np.array(cla_pred_)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_true, y_pred))

from sklearn.metrics import multilabel_confusion_matrix
multilabel_confusion_matrix(y_true, y_pred)

0.0196078431372549

array([[[42,  1],
        [ 7,  1]],

       [[46,  2],
        [ 2,  1]],

       [[48,  2],
        [ 0,  1]],

       [[51,  0],
        [ 0,  0]],

       [[43,  7],
        [ 1,  0]],

       [[49,  1],
        [ 1,  0]],

       [[51,  0],
        [ 0,  0]],

       [[46,  4],
        [ 1,  0]],

       [[49,  2],
        [ 0,  0]],

       [[51,  0],
        [ 0,  0]],

       [[49,  0],
        [ 2,  0]],

       [[50,  0],
        [ 1,  0]],

       [[47,  0],
        [ 4,  0]],

       [[ 1, 50],
        [ 0,  0]]])

In [102]:
from sklearn.metrics import classification_report

# label_names = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']
label_names = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12']

print(classification_report(y_true, y_pred, target_names=label_names))

              precision    recall  f1-score   support

        AB01       0.50      0.12      0.20         8
        AB02       0.33      0.33      0.33         3
        AB03       0.33      1.00      0.50         1
        AB04       0.00      0.00      0.00         0
        AB05       0.00      0.00      0.00         1
        AB06       0.00      0.00      0.00         1
        AB07       0.00      0.00      0.00         0
       AB081       0.00      0.00      0.00         1
       AB082       0.00      0.00      0.00         0
       AB083       0.00      0.00      0.00         0
        AB09       0.00      0.00      0.00         2
        AB10       0.00      0.00      0.00         1
        AB11       0.00      0.00      0.00         4
        AB12       0.00      0.00      0.00         0

   micro avg       0.04      0.14      0.06        22
   macro avg       0.08      0.10      0.07        22
weighted avg       0.24      0.14      0.14        22
 samples avg       0.02      0.06      0.03        22

/home/yupaporn/miniconda3/envs/USAI3/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/yupaporn/miniconda3/envs/USAI3/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/yupaporn/miniconda3/envs/USAI3/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/yupaporn/miniconda3/envs/USAI3/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

# Normal

In [32]:
normal = df
normal

,Unnamed: 0,Unnamed: 0.1,0,1,2,3,4,5,6,7,...,P ID,date,Path crop,Class,Sub_class_name,Sub_class,category,Prob,category_BiTNet,Prob_BiTNet
0,0,0,0.070262,0.613967,-0.144178,-0.133302,0.152672,0.177257,-0.094050,-0.097930,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.999987,Normal,0.576555
1,1,1,0.424074,0.373215,-0.190315,-0.057949,-0.046992,0.396701,0.121641,-0.017305,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.942473
2,2,2,0.887827,0.255022,-0.073275,-0.155301,-0.180442,0.398387,-0.110631,0.108062,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.995922,Normal,0.250000
3,3,3,0.124215,0.241486,-0.099518,-0.124972,-0.212320,0.218725,-0.138051,-0.132332,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.999326,Normal,0.465318
4,4,4,-0.029640,0.437044,-0.144407,-0.192584,0.280804,0.065014,-0.090790,-0.185189,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.633762
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
808,808,808,0.494716,0.158680,-0.072473,-0.118034,-0.160107,0.144856,-0.144092,-0.112001,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],AB12,0.998886,AB12,0.232227
809,809,809,0.862474,0.214631,-0.196177,-0.148607,-0.141830,-0.049645,-0.127183,0.034096,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.977855
810,810,810,0.731910,0.300760,-0.141567,-0.141887,0.099090,0.103995,-0.079066,-0.067519,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.987500
811,811,811,0.110222,-0.086056,0.015444,-0.166297,-0.207414,0.202673,-0.124514,-0.214145,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],AB12,0.999583,AB12,0.146717
812,812,812,0.280099,0.234322,-0.189338,-0.174745,-0.208500,0.035469,-0.138305,-0.173777,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.999239,Normal,0.598805

In [35]:
class_ = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']
col_name = ['Case', 'Act_label', 'Pred_label','Num_PredCase']
dff2 = pd.DataFrame(columns = col_name)

df_ = normal

case = list(set(df_['P ID']))
pred_label = []
num_case = []
act_label = []

for i in case:
    cas_pred = set(df_[df_['P ID'] == i]['category_BiTNet'])
    cas_act = list(df_[df_['P ID'] == i]['Sub_class'])
    pred_label.append(list(cas_pred))
    act_label.append(cas_act[0])
    num_case.append(len(cas_pred))

dff2['Pred_label'] = pred_label
dff2['Case'] = case
dff2['Num_PredCase'] = num_case
dff2['Act_label'] = act_label  

#แปลงข้อมูล    
Act_label = dff2['Act_label'].tolist()
Act_label_ =[]
for i in Act_label:   
    a = i.split("'")
    if len(a) ==5:
        m = a[1],a[3]
        g =[]
        for j in range(2):
            g.append(m[j])
        Act_label_.append(g)
    else:
        g =[]
        g.append(a[1])
        Act_label_.append(g)
dff2['Act_label'] = Act_label_
dff2

     Case      Act_label                          Pred_label  Num_PredCase
0    6668   [AB02, AB11]                      [Normal, AB12]             2
1    6798       [Normal]                      [Normal, AB12]             2
2    7725         [AB01]                      [Normal, AB12]             2
3    6446         [AB09]                [Normal, AB09, AB12]             3
4   12215       [Normal]                      [Normal, AB12]             2
5   12216       [Normal]                [Normal, AB04, AB12]             3
6   12217       [Normal]                      [Normal, AB01]             2
7   12218       [Normal]                      [Normal, AB12]             2
8   12219       [Normal]                      [Normal, AB12]             2
9   12220       [Normal]                      [Normal, AB12]             2
10  12221         [AB01]                      [Normal, AB12]             2
11  12222         [AB02]                      [Normal, AB12]             2
12  12285       [Normal]                      [Normal, AB12]             2
13   6600         [AB01]  [AB082, Normal, AB081, AB01, AB12]             5
14   6472  [AB06, AB081]                [Normal, AB05, AB12]             3
15  12279         [AB09]                      [Normal, AB12]             2
16   7895         [AB10]               [Normal, AB082, AB12]             3
17  12248       [Normal]                [Normal, AB05, AB12]             3
18  12280       [Normal]                      [Normal, AB12]             2
19   6621         [AB01]                      [Normal, AB12]             2
20   6624         [AB05]                [Normal, AB04, AB12]             3
21  12282       [Normal]                      [Normal, AB12]             2
22  12259         [AB01]                      [Normal, AB12]             2
23  12260       [Normal]                [Normal, AB07, AB12]             3
24  12261         [AB02]                      [Normal, AB12]             2
25  12262       [Normal]                      [Normal, AB12]             2
26  12263         [AB11]                      [Normal, AB12]             2
27  12264         [AB01]                [Normal, AB01, AB12]             3
28  12265         [AB03]          [Normal, AB03, AB02, AB12]             4
29  12266       [Normal]                      [Normal, AB12]             2
30  12283       [Normal]                            [Normal]             1
31  12284       [Normal]                            [Normal]             1
32  12269       [Normal]                            [Normal]             1
33  12270       [Normal]                      [Normal, AB12]             2
34  12271       [Normal]                      [Normal, AB12]             2
35   6640         [AB11]                      [Normal, AB12]             2
36  12273       [Normal]                      [Normal, AB12]             2
37  12274       [Normal]                      [Normal, AB12]             2
38  12275         [AB01]                [Normal, AB02, AB12]             3
39  12276       [Normal]               [Normal, AB12, AB081]             3
40  12277       [Normal]               [Normal, AB082, AB12]             3
41  12150       [Normal]                            [Normal]             1
42  12151       [Normal]                      [Normal, AB12]             2
43  12152       [Normal]                      [Normal, AB12]             2
44  12281       [Normal]         [Normal, AB05, AB12, AB081]             4
45  12154       [Normal]                      [Normal, AB12]             2
46  12155       [Normal]                     [Normal, AB081]             2
47  12156       [Normal]                      [Normal, AB12]             2
48   6525       [Normal]                      [Normal, AB12]             2
49  12158         [AB01]                      [Normal, AB12]             2
50   7039         [AB11]                [Normal, AB09, AB12]             3

In [37]:
TP = len(dff2[dff2['Act_label'] == dff2['Pred_label']])
TP

4

In [47]:
Act = dff2['Act_label'].tolist()
cla_act = []
for i in Act:
    if len(list(i)) == 1:
        if i == ['Normal']:
            a =[1,0]
            cla_act.append(a)
        else:
            a =[0,1]
            cla_act.append(a)
    else:
        a =[0,1]
        cla_act.append(a)
        
Pred = dff2['Pred_label'].tolist()
cla_pred = []
for i in Pred:
    if len(list(i)) == 1:
        if i == ['Normal']:
            a =[1,0]
            cla_pred.append(a)
        else:
            a =[0,1]
            cla_pred.append(a)
    else:
        a =[0,1]
        cla_pred.append(a)

In [80]:
dff2['Act'] = cla_act
dff2['Pred'] = cla_pred
dff2

,Case,Act_label,Pred_label,Num_PredCase,Act,Pred
0,6668,"[AB02, AB11]","[Normal, AB12]",2,"[0, 1]","[0, 1]"
1,6798,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
2,7725,[AB01],"[Normal, AB12]",2,"[0, 1]","[0, 1]"
3,6446,[AB09],"[Normal, AB09, AB12]",3,"[0, 1]","[0, 1]"
4,12215,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
5,12216,[Normal],"[Normal, AB04, AB12]",3,"[1, 0]","[0, 1]"
6,12217,[Normal],"[Normal, AB01]",2,"[1, 0]","[0, 1]"
7,12218,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
8,12219,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
9,12220,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
10,12221,[AB01],"[Normal, AB12]",2,"[0, 1]","[0, 1]"
11,12222,[AB02],"[Normal, AB12]",2,"[0, 1]","[0, 1]"
12,12285,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
13,6600,[AB01],"[AB082, Normal, AB081, AB01, AB12]",5,"[0, 1]","[0, 1]"
14,6472,"[AB06, AB081]","[Normal, AB05, AB12]",3,"[0, 1]","[0, 1]"
15,12279,[AB09],"[Normal, AB12]",2,"[0, 1]","[0, 1]"
16,7895,[AB10],"[Normal, AB082, AB12]",3,"[0, 1]","[0, 1]"
17,12248,[Normal],"[Normal, AB05, AB12]",3,"[1, 0]","[0, 1]"
18,12280,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
19,6621,[AB01],"[Normal, AB12]",2,"[0, 1]","[0, 1]"
20,6624,[AB05],"[Normal, AB04, AB12]",3,"[0, 1]","[0, 1]"
21,12282,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
22,12259,[AB01],"[Normal, AB12]",2,"[0, 1]","[0, 1]"
23,12260,[Normal],"[Normal, AB07, AB12]",3,"[1, 0]","[0, 1]"
24,12261,[AB02],"[Normal, AB12]",2,"[0, 1]","[0, 1]"
25,12262,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
26,12263,[AB11],"[Normal, AB12]",2,"[0, 1]","[0, 1]"
27,12264,[AB01],"[Normal, AB01, AB12]",3,"[0, 1]","[0, 1]"
28,12265,[AB03],"[Normal, AB03, AB02, AB12]",4,"[0, 1]","[0, 1]"
29,12266,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
30,12283,[Normal],[Normal],1,"[1, 0]","[1, 0]"
31,12284,[Normal],[Normal],1,"[1, 0]","[1, 0]"
32,12269,[Normal],[Normal],1,"[1, 0]","[1, 0]"
33,12270,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
34,12271,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
35,6640,[AB11],"[Normal, AB12]",2,"[0, 1]","[0, 1]"
36,12273,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
37,12274,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
38,12275,[AB01],"[Normal, AB02, AB12]",3,"[0, 1]","[0, 1]"
39,12276,[Normal],"[Normal, AB12, AB081]",3,"[1, 0]","[0, 1]"
40,12277,[Normal],"[Normal, AB082, AB12]",3,"[1, 0]","[0, 1]"
41,12150,[Normal],[Normal],1,"[1, 0]","[1, 0]"
42,12151,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
43,12152,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
44,12281,[Normal],"[Normal, AB05, AB12, AB081]",4,"[1, 0]","[0, 1]"
45,12154,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
46,12155,[Normal],"[Normal, AB081]",2,"[1, 0]","[0, 1]"
47,12156,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
48,6525,[Normal],"[Normal, AB12]",2,"[1, 0]","[0, 1]"
49,12158,[AB01],"[Normal, AB12]",2,"[0, 1]","[0, 1]"
50,7039,[AB11],"[Normal, AB09, AB12]",3,"[0, 1]","[0, 1]"

In [ ]:
normal = df[df['Class'] == 'Normal']

class_ = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']
col_name = ['Case', 'Act_label', 'Pred_label','Num_PredCase']
dff2 = pd.DataFrame(columns = col_name)

df_ = normal

case = list(set(df_['P ID']))
pred_label = []
num_case = []
act_label = []

for i in case:
    cas_pred = set(df_[df_['P ID'] == i]['category_BiTNet'])
    cas_act = list(df_[df_['P ID'] == i]['Sub_class'])
    pred_label.append(list(cas_pred))
    act_label.append(cas_act[0])
    num_case.append(len(cas_pred))

dff2['Pred_label'] = pred_label
dff2['Case'] = case
dff2['Num_PredCase'] = num_case
dff2['Act_label'] = act_label  

#แปลงข้อมูล    
Act_label = dff2['Act_label'].tolist()
Act_label_ =[]
for i in Act_label:   
    a = i.split("'")
    if len(a) ==5:
        m = a[1],a[3]
        g =[]
        for j in range(2):
            g.append(m[j])
        Act_label_.append(g)
    else:
        g =[]
        g.append(a[1])
        Act_label_.append(g)
dff2['Act_label'] = Act_label_
dff0 = dff2

Act = dff2['Act_label'].tolist()
cla_act = []
for i in Act:
    if len(list(i)) == 1:
        if i == ['Normal']:
            a =[1,0]
            cla_act.append(a)
        else:
            a =[0,1]
            cla_act.append(a)
    else:
        a =[0,1]
        cla_act.append(a)
        
Pred = dff2['Pred_label'].tolist()
cla_pred = []
for i in Pred:
    if len(list(i)) == 1:
        if i == ['Normal']:
            a =[1,0]
            cla_pred.append(a)
        else:
            a =[0,1]
            cla_pred.append(a)
    else:
        a =[0,1]
        cla_pred.append(a)
        
dff2['Act'] = cla_act
dff2['Pred'] = cla_pred
dff2

In [65]:
TP = len(dff2[dff2['Act_label'] == dff2['Pred_label']])
TP

4

In [64]:
FP = len(dff2[dff2['Act_label'] != dff2['Pred_label']])
FP

47

In [57]:
len(dff2[dff2['Act_label'] != dff2['Pred_label']])

['Normal']

In [87]:
dff2['Pred'] == [0, 1]

ValueError: ('Lengths must match to compare', (51,), (2,))

In [89]:
print(list(dff2['Pred'])[0][0])

0

In [76]:
dff2.dtypes

Case             int64
Act_label       object
Pred_label      object
Num_PredCase     int64
Act             object
Pred            object
dtype: object