In [83]:
import pandas as pd
df = pd.read_csv( '/home/yupaporn/CSV_file/result_BiTNet_FPScores.csv')#แก้

In [84]:
df

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,Spilt,15AB_FPPred_3,Prob_FPPred_3,15AB_pred,Prob_pred,15AB_FPAct_3,Prob_FPAct_3,15AB_pred_,15AB_FPPred_3_,15AB_FPAct_3_
0,0,AB01_40,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Test,Normal,0.413035,Normal,0.413035,Normal,0.413035,Incorrect,Incorrect,Incorrect
1,1,AB01_40,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Test,AB01,0.110668,AB01,0.110668,AB01,0.110668,Correct,Correct,Correct
2,2,AB01_40,P4,P41,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,Test,AB02,0.091490,AB02,0.091490,AB02,0.091490,Incorrect,Incorrect,Incorrect
3,3,AB01_40,P5,P51,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,2,MildFattyLiver,...,Test,AB01,0.075286,AB01,0.075286,AB01,0.075286,Correct,Correct,Correct
4,4,AB01_40,P3,P31,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,Test,AB02,0.065060,AB02,0.065060,AB02,0.065060,Incorrect,Incorrect,Incorrect
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,1307,350,P3,P32,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-B,2,Normal,...,Test,Normal,1.000000,Normal,1.000000,Normal,1.000000,Correct,Correct,Correct
1308,1308,350,P4,P42,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-B,2,Normal,...,Test,Normal,0.515819,Normal,0.515819,Normal,0.515819,Correct,Correct,Correct
1309,1309,350,P5,P52,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-C,2,Normal,...,Test,Normal,0.995000,Normal,0.995000,Normal,0.995000,Correct,Correct,Correct
1310,1310,350,P6,P61,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-C,2,Normal,...,Test,Normal,0.906968,Normal,0.906968,Normal,0.906968,Correct,Correct,Correct
1311,1311,350,P8,P8,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-E,2,Normal,...,Test,Normal,0.987972,Normal,0.987972,Normal,0.987972,Correct,Correct,Correct

In [85]:
# df = df.replace({'15AB': {'RenalParenchymalchange': 'RenalParenchymalChange', 'Renalstones': 'RenalStone', 'RenalstonesHydronephrosis': 'RenalstonesAndHydronephrosis'}})
# df.to_csv('/home/yupaporn/CSV_file/result_BiTNet_FPScores.csv', index=False)

In [86]:
df.columns

Index(['Unnamed: 0', 'Case', 'Abs Position', 'Sub Position', 'Class',
       'Path Full', 'Path Crop', 'Views', 'fold', '15AB', 'originalImage',
       'left', 'top', 'width', 'height', 'Rleft', 'Rtop', 'Rwidth', 'Rheight',
       'Sub_class_New', 'tag_AjNit', 'tag_AjWan', 'Test150', 'Spilt',
       '15AB_FPPred_3', 'Prob_FPPred_3', '15AB_pred', 'Prob_pred',
       '15AB_FPAct_3', 'Prob_FPAct_3', '15AB_pred_', '15AB_FPPred_3_',
       '15AB_FPAct_3_'],
      dtype='object')

In [87]:
res = df

#None
AI_pred = res['15AB_pred'].tolist()
act = res['Sub_class_New'].tolist()
Acc  = []
Acc_  = []
for i in  range(len(AI_pred)):
    if act[i] == AI_pred[i]:
        Acc.append('Correct')
    else:
        Acc.append('Incorrect')

res['15AB_pred_'] =Acc

#None
AI_pred = res['15AB_FPPred_3'].tolist()
act = res['Sub_class_New'].tolist()
Acc  = []
Acc_  = []
for i in  range(len(AI_pred)):
    if act[i] == AI_pred[i]:
        Acc.append('Correct')
    else:
        Acc.append('Incorrect')

res['15AB_FPPred_3_'] =Acc

#None
AI_pred = res['15AB_FPAct_3'].tolist()
act = res['Sub_class_New'].tolist()
Acc  = []
Acc_  = []
for i in  range(len(AI_pred)):
    if act[i] == AI_pred[i]:
        Acc.append('Correct')
    else:
        Acc.append('Incorrect')

res['15AB_FPAct_3_'] =Acc

In [88]:
df.columns

Index(['Unnamed: 0', 'Case', 'Abs Position', 'Sub Position', 'Class',
       'Path Full', 'Path Crop', 'Views', 'fold', '15AB', 'originalImage',
       'left', 'top', 'width', 'height', 'Rleft', 'Rtop', 'Rwidth', 'Rheight',
       'Sub_class_New', 'tag_AjNit', 'tag_AjWan', 'Test150', 'Spilt',
       '15AB_FPPred_3', 'Prob_FPPred_3', '15AB_pred', 'Prob_pred',
       '15AB_FPAct_3', 'Prob_FPAct_3', '15AB_pred_', '15AB_FPPred_3_',
       '15AB_FPAct_3_'],
      dtype='object')

In [89]:
df[["Sub_class_New","15AB" ,"Case"]].groupby(['Sub_class_New',"15AB"]).count().reset_index()

   Sub_class_New                            15AB  Case
0           AB01                  MildFattyLiver    74
1           AB02              ModerateFattyLiver    59
2           AB03                SevereFattyLiver    19
3           AB04                       Cirrhosis    38
4           AB05                            PDF1    29
5           AB06                            PDF2    21
6           AB07                            PDF3    21
7          AB081                       Livermass    32
8          AB082                             BDD    28
9          AB083                 LivermassAndBDD    11
10          AB09                Gallbladderstone    26
11          AB10                 GallbladderMass     1
12          AB10                Gallbladderpolyp     9
13          AB11                  Hydronephrosis    18
14          AB11                       RenalCyst     2
15          AB11               RenalCystAndStone     1
16          AB11                       RenalMass     1
17          AB11                      RenalStone    19
18          AB11  RenalstoneAndParenchymalChange     2
19          AB11    RenalstonesAndHydronephrosis    12
20          AB12                    Splenomegaly    32
21        Normal                          Normal   857

# None

# ทำนายผิดเเค่ไหนหาสัดสัดอิงตามจำนวน class ที่ทำนาย

In [101]:
df.head()

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,Spilt,15AB_FPPred_3,Prob_FPPred_3,15AB_pred,Prob_pred,15AB_FPAct_3,Prob_FPAct_3,15AB_pred_,15AB_FPPred_3_,15AB_FPAct_3_
0,0,AB01_40,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Test,Normal,0.413035,Normal,0.413035,Normal,0.413035,Incorrect,Incorrect,Incorrect
1,1,AB01_40,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Test,AB01,0.110668,AB01,0.110668,AB01,0.110668,Correct,Correct,Correct
2,2,AB01_40,P4,P41,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,Test,AB02,0.091490,AB02,0.091490,AB02,0.091490,Incorrect,Incorrect,Incorrect
3,3,AB01_40,P5,P51,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,2,MildFattyLiver,...,Test,AB01,0.075286,AB01,0.075286,AB01,0.075286,Correct,Correct,Correct
4,4,AB01_40,P3,P31,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,Test,AB02,0.065060,AB02,0.065060,AB02,0.065060,Incorrect,Incorrect,Incorrect

In [105]:
df[["15AB_pred", "15AB_pred_", "Unnamed: 0"]].groupby(["15AB_pred", "15AB_pred_"]).count().reset_index()

   15AB_pred 15AB_pred_  Unnamed: 0
0       AB01    Correct          45
1       AB01  Incorrect          12
2       AB02    Correct          35
3       AB02  Incorrect          26
4       AB03    Correct           9
5       AB03  Incorrect           9
6       AB04    Correct          26
7       AB04  Incorrect           6
8       AB05    Correct          19
9       AB05  Incorrect           4
10      AB06    Correct          10
11      AB06  Incorrect           2
12      AB07    Correct          10
13      AB07  Incorrect           4
14     AB081    Correct          18
15     AB081  Incorrect           5
16     AB082    Correct          15
17     AB082  Incorrect           4
18     AB083    Correct           4
19     AB083  Incorrect           1
20      AB09    Correct          20
21      AB10    Correct           4
22      AB10  Incorrect           1
23      AB11    Correct          20
24      AB11  Incorrect           2
25      AB12    Correct          24
26      AB12  Incorrect          33
27    Normal    Correct         852
28    Normal  Incorrect          92

## ทำนายผิดเเค่ไหนหาสัดสัดอิงตามจำนวน class จริง

In [90]:
Correct = df[df['15AB_pred_'] == 'Correct']
Incorrect = df[df['15AB_pred_'] == 'Incorrect']

In [91]:
Incorrect[['Sub_class_New', '15AB_pred']]

     Sub_class_New 15AB_pred
0             AB01    Normal
2             AB01      AB02
4             AB01      AB02
8             AB02      AB03
13            AB06    Normal
...            ...       ...
969         Normal      AB01
1117        Normal      AB05
1291        Normal      AB04
1294        Normal      AB05
1305        Normal      AB11

[201 rows x 2 columns]

In [92]:
Incorrect[["Sub_class_New","15AB" ,"15AB_pred","Case"]].groupby(['Sub_class_New',"15AB","15AB_pred"]).count().reset_index()

   Sub_class_New                          15AB 15AB_pred  Case
0           AB01                MildFattyLiver      AB02    16
1           AB01                MildFattyLiver    Normal    13
2           AB02            ModerateFattyLiver      AB01     9
3           AB02            ModerateFattyLiver      AB03     9
4           AB02            ModerateFattyLiver      AB10     1
5           AB02            ModerateFattyLiver    Normal     5
6           AB03              SevereFattyLiver      AB02    10
7           AB04                     Cirrhosis      AB06     1
8           AB04                     Cirrhosis      AB07     1
9           AB04                     Cirrhosis     AB081     1
10          AB04                     Cirrhosis    Normal     9
11          AB05                          PDF1     AB081     1
12          AB05                          PDF1    Normal     9
13          AB06                          PDF2      AB05     1
14          AB06                          PDF2      AB07     2
15          AB06                          PDF2    Normal     8
16          AB07                          PDF3      AB06     1
17          AB07                          PDF3    Normal    10
18         AB081                     Livermass      AB01     2
19         AB081                     Livermass      AB12     2
20         AB081                     Livermass    Normal    10
21         AB082                           BDD      AB05     1
22         AB082                           BDD     AB081     3
23         AB082                           BDD     AB083     1
24         AB082                           BDD      AB11     1
25         AB082                           BDD    Normal     7
26         AB083               LivermassAndBDD      AB04     1
27         AB083               LivermassAndBDD     AB082     4
28         AB083               LivermassAndBDD    Normal     2
29          AB09              Gallbladderstone      AB07     1
30          AB09              Gallbladderstone      AB12     1
31          AB09              Gallbladderstone    Normal     4
32          AB10               GallbladderMass    Normal     1
33          AB10              Gallbladderpolyp    Normal     5
34          AB11                Hydronephrosis      AB12    13
35          AB11                Hydronephrosis    Normal     1
36          AB11                     RenalCyst    Normal     1
37          AB11                    RenalStone      AB12    12
38          AB11                    RenalStone    Normal     3
39          AB11  RenalstonesAndHydronephrosis      AB12     5
40          AB12                  Splenomegaly      AB04     4
41          AB12                  Splenomegaly    Normal     4
42        Normal                        Normal      AB01     1
43        Normal                        Normal      AB04     1
44        Normal                        Normal      AB05     2
45        Normal                        Normal      AB11     1

# แบบที่ 3 +FPAct

## ทำนายผิดเเค่ไหนหาสัดสัดอิงตามจำนวน class ที่ทำนาย

In [106]:
df[["15AB_FPAct_3", "15AB_FPAct_3_", "Unnamed: 0"]].groupby(["15AB_FPAct_3", "15AB_FPAct_3_"]).count().reset_index()

   15AB_FPAct_3 15AB_FPAct_3_  Unnamed: 0
0          AB01       Correct          45
1          AB01     Incorrect          13
2          AB02       Correct          35
3          AB02     Incorrect          26
4          AB03       Correct           9
5          AB03     Incorrect          10
6          AB04       Correct          26
7          AB04     Incorrect           6
8          AB05       Correct          19
9          AB05     Incorrect           5
10         AB06       Correct          11
11         AB06     Incorrect           1
12         AB07       Correct          11
13         AB07     Incorrect           3
14        AB081       Correct          19
15        AB081     Incorrect           6
16        AB082       Correct          16
17        AB082     Incorrect           4
18        AB083       Correct           3
19         AB09       Correct          21
20         AB10       Correct           4
21         AB11       Correct          22
22         AB11     Incorrect           1
23         AB12       Correct          23
24         AB12     Incorrect          28
25       Normal       Correct         853
26       Normal     Incorrect          92

## ทำนายผิดเเค่ไหนหาสัดสัดอิงตามจำนวน class จริง

In [98]:
Correct = df[df['15AB_FPAct_3_'] == 'Correct']
Incorrect = df[df['15AB_FPAct_3_'] == 'Incorrect']

In [99]:
Incorrect[["Sub_class_New","15AB" ,"15AB_FPAct_3","Case"]].groupby(['Sub_class_New',"15AB","15AB_FPAct_3"]).count().reset_index()

   Sub_class_New                          15AB 15AB_FPAct_3  Case
0           AB01                MildFattyLiver         AB02    16
1           AB01                MildFattyLiver       Normal    13
2           AB02            ModerateFattyLiver         AB01    10
3           AB02            ModerateFattyLiver         AB03     9
4           AB02            ModerateFattyLiver       Normal     5
5           AB03              SevereFattyLiver         AB02    10
6           AB04                     Cirrhosis         AB06     1
7           AB04                     Cirrhosis         AB07     1
8           AB04                     Cirrhosis        AB081     1
9           AB04                     Cirrhosis       Normal     9
10          AB05                          PDF1        AB081     1
11          AB05                          PDF1       Normal     9
12          AB06                          PDF2         AB05     1
13          AB06                          PDF2         AB07     1
14          AB06                          PDF2       Normal     8
15          AB07                          PDF3       Normal    10
16         AB081                     Livermass         AB01     2
17         AB081                     Livermass         AB03     1
18         AB081                     Livermass       Normal    10
19         AB082                           BDD         AB05     1
20         AB082                           BDD        AB081     4
21         AB082                           BDD       Normal     7
22         AB083               LivermassAndBDD         AB04     1
23         AB083               LivermassAndBDD         AB05     1
24         AB083               LivermassAndBDD        AB082     4
25         AB083               LivermassAndBDD       Normal     2
26          AB09              Gallbladderstone         AB07     1
27          AB09              Gallbladderstone       Normal     4
28          AB10               GallbladderMass       Normal     1
29          AB10              Gallbladderpolyp       Normal     5
30          AB11                Hydronephrosis         AB12    11
31          AB11                Hydronephrosis       Normal     1
32          AB11                     RenalCyst       Normal     1
33          AB11                    RenalStone         AB12    12
34          AB11                    RenalStone       Normal     3
35          AB11  RenalstonesAndHydronephrosis         AB12     5
36          AB12                  Splenomegaly         AB04     4
37          AB12                  Splenomegaly         AB11     1
38          AB12                  Splenomegaly       Normal     4
39        Normal                        Normal         AB01     1
40        Normal                        Normal         AB04     1
41        Normal                        Normal         AB05     2

# แบบที่ 3 +FPPred

In [95]:
df

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,Spilt,15AB_FPPred_3,Prob_FPPred_3,15AB_pred,Prob_pred,15AB_FPAct_3,Prob_FPAct_3,15AB_pred_,15AB_FPPred_3_,15AB_FPAct_3_
0,0,AB01_40,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Test,Normal,0.413035,Normal,0.413035,Normal,0.413035,Incorrect,Incorrect,Incorrect
1,1,AB01_40,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Test,AB01,0.110668,AB01,0.110668,AB01,0.110668,Correct,Correct,Correct
2,2,AB01_40,P4,P41,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,Test,AB02,0.091490,AB02,0.091490,AB02,0.091490,Incorrect,Incorrect,Incorrect
3,3,AB01_40,P5,P51,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,2,MildFattyLiver,...,Test,AB01,0.075286,AB01,0.075286,AB01,0.075286,Correct,Correct,Correct
4,4,AB01_40,P3,P31,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,Test,AB02,0.065060,AB02,0.065060,AB02,0.065060,Incorrect,Incorrect,Incorrect
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,1307,350,P3,P32,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-B,2,Normal,...,Test,Normal,1.000000,Normal,1.000000,Normal,1.000000,Correct,Correct,Correct
1308,1308,350,P4,P42,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-B,2,Normal,...,Test,Normal,0.515819,Normal,0.515819,Normal,0.515819,Correct,Correct,Correct
1309,1309,350,P5,P52,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-C,2,Normal,...,Test,Normal,0.995000,Normal,0.995000,Normal,0.995000,Correct,Correct,Correct
1310,1310,350,P6,P61,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-C,2,Normal,...,Test,Normal,0.906968,Normal,0.906968,Normal,0.906968,Correct,Correct,Correct
1311,1311,350,P8,P8,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-E,2,Normal,...,Test,Normal,0.987972,Normal,0.987972,Normal,0.987972,Correct,Correct,Correct

In [96]:
Correct = df[df['15AB_FPPred_3_'] == 'Correct']
Incorrect = df[df['15AB_FPPred_3_'] == 'Incorrect']

In [97]:
Incorrect[["Sub_class_New","15AB" ,"15AB_FPPred_3","Case"]].groupby(['Sub_class_New',"15AB","15AB_FPPred_3"]).count().reset_index()

   Sub_class_New                          15AB 15AB_FPPred_3  Case
0           AB01                MildFattyLiver          AB02    16
1           AB01                MildFattyLiver        Normal    13
2           AB02            ModerateFattyLiver          AB01    10
3           AB02            ModerateFattyLiver          AB03     9
4           AB02            ModerateFattyLiver        Normal     5
5           AB03              SevereFattyLiver          AB02     9
6           AB03              SevereFattyLiver        Normal     1
7           AB04                     Cirrhosis          AB06     1
8           AB04                     Cirrhosis          AB07     1
9           AB04                     Cirrhosis         AB081     1
10          AB04                     Cirrhosis        Normal     9
11          AB05                          PDF1         AB081     1
12          AB05                          PDF1        Normal     9
13          AB06                          PDF2          AB05     1
14          AB06                          PDF2          AB07     2
15          AB06                          PDF2        Normal     8
16          AB07                          PDF3        Normal    10
17         AB081                     Livermass          AB01     2
18         AB081                     Livermass          AB03     1
19         AB081                     Livermass        Normal    10
20         AB082                           BDD          AB05     1
21         AB082                           BDD         AB081     4
22         AB082                           BDD          AB11     1
23         AB082                           BDD        Normal     7
24         AB083               LivermassAndBDD          AB04     1
25         AB083               LivermassAndBDD          AB05     1
26         AB083               LivermassAndBDD         AB082     4
27         AB083               LivermassAndBDD        Normal     2
28          AB09              Gallbladderstone          AB07     1
29          AB09              Gallbladderstone          AB12     1
30          AB09              Gallbladderstone        Normal     4
31          AB10               GallbladderMass        Normal     1
32          AB10              Gallbladderpolyp        Normal     5
33          AB11                Hydronephrosis          AB12    13
34          AB11                Hydronephrosis        Normal     1
35          AB11                     RenalCyst        Normal     1
36          AB11                    RenalStone          AB12    11
37          AB11                    RenalStone        Normal     3
38          AB11  RenalstonesAndHydronephrosis          AB12     5
39          AB12                  Splenomegaly          AB04     4
40          AB12                  Splenomegaly        Normal     4
41        Normal                        Normal          AB01     1
42        Normal                        Normal          AB04     1
43        Normal                        Normal          AB05     2