In [83]:
import pandas as pd
df = pd.read_csv( '/home/yupaporn/CSV_file/result_BiTNet_FPScores.csv')#แก้

In [84]:
df

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,Spilt,15AB_FPPred_3,Prob_FPPred_3,15AB_pred,Prob_pred,15AB_FPAct_3,Prob_FPAct_3,15AB_pred_,15AB_FPPred_3_,15AB_FPAct_3_
0,0,AB01_40,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Test,Normal,0.413035,Normal,0.413035,Normal,0.413035,Incorrect,Incorrect,Incorrect
1,1,AB01_40,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Test,AB01,0.110668,AB01,0.110668,AB01,0.110668,Correct,Correct,Correct
2,2,AB01_40,P4,P41,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,Test,AB02,0.091490,AB02,0.091490,AB02,0.091490,Incorrect,Incorrect,Incorrect
3,3,AB01_40,P5,P51,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,2,MildFattyLiver,...,Test,AB01,0.075286,AB01,0.075286,AB01,0.075286,Correct,Correct,Correct
4,4,AB01_40,P3,P31,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,Test,AB02,0.065060,AB02,0.065060,AB02,0.065060,Incorrect,Incorrect,Incorrect
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,1307,350,P3,P32,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-B,2,Normal,...,Test,Normal,1.000000,Normal,1.000000,Normal,1.000000,Correct,Correct,Correct
1308,1308,350,P4,P42,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-B,2,Normal,...,Test,Normal,0.515819,Normal,0.515819,Normal,0.515819,Correct,Correct,Correct
1309,1309,350,P5,P52,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-C,2,Normal,...,Test,Normal,0.995000,Normal,0.995000,Normal,0.995000,Correct,Correct,Correct
1310,1310,350,P6,P61,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-C,2,Normal,...,Test,Normal,0.906968,Normal,0.906968,Normal,0.906968,Correct,Correct,Correct
1311,1311,350,P8,P8,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-E,2,Normal,...,Test,Normal,0.987972,Normal,0.987972,Normal,0.987972,Correct,Correct,Correct

In [85]:
# df = df.replace({'15AB': {'RenalParenchymalchange': 'RenalParenchymalChange', 'Renalstones': 'RenalStone', 'RenalstonesHydronephrosis': 'RenalstonesAndHydronephrosis'}})
# df.to_csv('/home/yupaporn/CSV_file/result_BiTNet_FPScores.csv', index=False)

In [86]:
df.columns

Index(['Unnamed: 0', 'Case', 'Abs Position', 'Sub Position', 'Class',
       'Path Full', 'Path Crop', 'Views', 'fold', '15AB', 'originalImage',
       'left', 'top', 'width', 'height', 'Rleft', 'Rtop', 'Rwidth', 'Rheight',
       'Sub_class_New', 'tag_AjNit', 'tag_AjWan', 'Test150', 'Spilt',
       '15AB_FPPred_3', 'Prob_FPPred_3', '15AB_pred', 'Prob_pred',
       '15AB_FPAct_3', 'Prob_FPAct_3', '15AB_pred_', '15AB_FPPred_3_',
       '15AB_FPAct_3_'],
      dtype='object')

In [87]:
res = df

#None
AI_pred = res['15AB_pred'].tolist()
act = res['Sub_class_New'].tolist()
Acc  = []
Acc_  = []
for i in  range(len(AI_pred)):
    if act[i] == AI_pred[i]:
        Acc.append('Correct')
    else:
        Acc.append('Incorrect')

res['15AB_pred_'] =Acc

#None
AI_pred = res['15AB_FPPred_3'].tolist()
act = res['Sub_class_New'].tolist()
Acc  = []
Acc_  = []
for i in  range(len(AI_pred)):
    if act[i] == AI_pred[i]:
        Acc.append('Correct')
    else:
        Acc.append('Incorrect')

res['15AB_FPPred_3_'] =Acc

#None
AI_pred = res['15AB_FPAct_3'].tolist()
act = res['Sub_class_New'].tolist()
Acc  = []
Acc_  = []
for i in  range(len(AI_pred)):
    if act[i] == AI_pred[i]:
        Acc.append('Correct')
    else:
        Acc.append('Incorrect')

res['15AB_FPAct_3_'] =Acc

In [88]:
df.columns

Index(['Unnamed: 0', 'Case', 'Abs Position', 'Sub Position', 'Class',
       'Path Full', 'Path Crop', 'Views', 'fold', '15AB', 'originalImage',
       'left', 'top', 'width', 'height', 'Rleft', 'Rtop', 'Rwidth', 'Rheight',
       'Sub_class_New', 'tag_AjNit', 'tag_AjWan', 'Test150', 'Spilt',
       '15AB_FPPred_3', 'Prob_FPPred_3', '15AB_pred', 'Prob_pred',
       '15AB_FPAct_3', 'Prob_FPAct_3', '15AB_pred_', '15AB_FPPred_3_',
       '15AB_FPAct_3_'],
      dtype='object')

In [89]:
df[["Sub_class_New","15AB" ,"Case"]].groupby(['Sub_class_New',"15AB"]).count().reset_index()

   Sub_class_New                            15AB  Case
0           AB01                  MildFattyLiver    74
1           AB02              ModerateFattyLiver    59
2           AB03                SevereFattyLiver    19
3           AB04                       Cirrhosis    38
4           AB05                            PDF1    29
5           AB06                            PDF2    21
6           AB07                            PDF3    21
7          AB081                       Livermass    32
8          AB082                             BDD    28
9          AB083                 LivermassAndBDD    11
10          AB09                Gallbladderstone    26
11          AB10                 GallbladderMass     1
12          AB10                Gallbladderpolyp     9
13          AB11                  Hydronephrosis    18
14          AB11                       RenalCyst     2
15          AB11               RenalCystAndStone     1
16          AB11                       RenalMass     1
17          AB11                      RenalStone    19
18          AB11  RenalstoneAndParenchymalChange     2
19          AB11    RenalstonesAndHydronephrosis    12
20          AB12                    Splenomegaly    32
21        Normal                          Normal   857

# None

# ทำนายผิดเเค่ไหนหาสัดสัดอิงตามจำนวน class ที่ทำนาย

In [101]:
df.head()

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,Spilt,15AB_FPPred_3,Prob_FPPred_3,15AB_pred,Prob_pred,15AB_FPAct_3,Prob_FPAct_3,15AB_pred_,15AB_FPPred_3_,15AB_FPAct_3_
0,0,AB01_40,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Test,Normal,0.413035,Normal,0.413035,Normal,0.413035,Incorrect,Incorrect,Incorrect
1,1,AB01_40,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Test,AB01,0.110668,AB01,0.110668,AB01,0.110668,Correct,Correct,Correct
2,2,AB01_40,P4,P41,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,Test,AB02,0.091490,AB02,0.091490,AB02,0.091490,Incorrect,Incorrect,Incorrect
3,3,AB01_40,P5,P51,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,2,MildFattyLiver,...,Test,AB01,0.075286,AB01,0.075286,AB01,0.075286,Correct,Correct,Correct
4,4,AB01_40,P3,P31,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,Test,AB02,0.065060,AB02,0.065060,AB02,0.065060,Incorrect,Incorrect,Incorrect

In [105]:
df[["15AB_pred", "15AB_pred_", "Unnamed: 0"]].groupby(["15AB_pred", "15AB_pred_"]).count().reset_index()

   15AB_pred 15AB_pred_  Unnamed: 0
0       AB01    Correct          45
1       AB01  Incorrect          12
2       AB02    Correct          35
3       AB02  Incorrect          26
4       AB03    Correct           9
5       AB03  Incorrect           9
6       AB04    Correct          26
7       AB04  Incorrect           6
8       AB05    Correct          19
9       AB05  Incorrect           4
10      AB06    Correct          10
11      AB06  Incorrect           2
12      AB07    Correct          10
13      AB07  Incorrect           4
14     AB081    Correct          18
15     AB081  Incorrect           5
16     AB082    Correct          15
17     AB082  Incorrect           4
18     AB083    Correct           4
19     AB083  Incorrect           1
20      AB09    Correct          20
21      AB10    Correct           4
22      AB10  Incorrect           1
23      AB11    Correct          20
24      AB11  Incorrect           2
25      AB12    Correct          24
26      AB12  Incorrect          33
27    Normal    Correct         852
28    Normal  Incorrect          92

## ทำนายผิดเเค่ไหนหาสัดสัดอิงตามจำนวน class จริง

In [90]:
Correct = df[df['15AB_pred_'] == 'Correct']
Incorrect = df[df['15AB_pred_'] == 'Incorrect']

In [91]:
Incorrect[['Sub_class_New', '15AB_pred']]

     Sub_class_New 15AB_pred
0             AB01    Normal
2             AB01      AB02
4             AB01      AB02
8             AB02      AB03
13            AB06    Normal
...            ...       ...
969         Normal      AB01
1117        Normal      AB05
1291        Normal      AB04
1294        Normal      AB05
1305        Normal      AB11

[201 rows x 2 columns]

In [92]:
Incorrect[["Sub_class_New","15AB" ,"15AB_pred","Case"]].groupby(['Sub_class_New',"15AB","15AB_pred"]).count().reset_index()

   Sub_class_New                          15AB 15AB_pred  Case
0           AB01                MildFattyLiver      AB02    16
1           AB01                MildFattyLiver    Normal    13
2           AB02            ModerateFattyLiver      AB01     9
3           AB02            ModerateFattyLiver      AB03     9
4           AB02            ModerateFattyLiver      AB10     1
5           AB02            ModerateFattyLiver    Normal     5
6           AB03              SevereFattyLiver      AB02    10
7           AB04                     Cirrhosis      AB06     1
8           AB04                     Cirrhosis      AB07     1
9           AB04                     Cirrhosis     AB081     1
10          AB04                     Cirrhosis    Normal     9
11          AB05                          PDF1     AB081     1
12          AB05                          PDF1    Normal     9
13          AB06                          PDF2      AB05     1
14          AB06                          PDF2      AB07     2
15          AB06                          PDF2    Normal     8
16          AB07                          PDF3      AB06     1
17          AB07                          PDF3    Normal    10
18         AB081                     Livermass      AB01     2
19         AB081                     Livermass      AB12     2
20         AB081                     Livermass    Normal    10
21         AB082                           BDD      AB05     1
22         AB082                           BDD     AB081     3
23         AB082                           BDD     AB083     1
24         AB082                           BDD      AB11     1
25         AB082                           BDD    Normal     7
26         AB083               LivermassAndBDD      AB04     1
27         AB083               LivermassAndBDD     AB082     4
28         AB083               LivermassAndBDD    Normal     2
29          AB09              Gallbladderstone      AB07     1
30          AB09              Gallbladderstone      AB12     1
31          AB09              Gallbladderstone    Normal     4
32          AB10               GallbladderMass    Normal     1
33          AB10              Gallbladderpolyp    Normal     5
34          AB11                Hydronephrosis      AB12    13
35          AB11                Hydronephrosis    Normal     1
36          AB11                     RenalCyst    Normal     1
37          AB11                    RenalStone      AB12    12
38          AB11                    RenalStone    Normal     3
39          AB11  RenalstonesAndHydronephrosis      AB12     5
40          AB12                  Splenomegaly      AB04     4
41          AB12                  Splenomegaly    Normal     4
42        Normal                        Normal      AB01     1
43        Normal                        Normal      AB04     1
44        Normal                        Normal      AB05     2
45        Normal                        Normal      AB11     1

# แบบที่ 3 +FPAct

## ทำนายผิดเเค่ไหนหาสัดสัดอิงตามจำนวน class ที่ทำนาย

In [106]:
df[["15AB_FPAct_3", "15AB_FPAct_3_", "Unnamed: 0"]].groupby(["15AB_FPAct_3", "15AB_FPAct_3_"]).count().reset_index()

   15AB_FPAct_3 15AB_FPAct_3_  Unnamed: 0
0          AB01       Correct          45
1          AB01     Incorrect          13
2          AB02       Correct          35
3          AB02     Incorrect          26
4          AB03       Correct           9
5          AB03     Incorrect          10
6          AB04       Correct          26
7          AB04     Incorrect           6
8          AB05       Correct          19
9          AB05     Incorrect           5
10         AB06       Correct          11
11         AB06     Incorrect           1
12         AB07       Correct          11
13         AB07     Incorrect           3
14        AB081       Correct          19
15        AB081     Incorrect           6
16        AB082       Correct          16
17        AB082     Incorrect           4
18        AB083       Correct           3
19         AB09       Correct          21
20         AB10       Correct           4
21         AB11       Correct          22
22         AB11     Incorrect           1
23         AB12       Correct          23
24         AB12     Incorrect          28
25       Normal       Correct         853
26       Normal     Incorrect          92

## ทำนายผิดเเค่ไหนหาสัดสัดอิงตามจำนวน class จริง

In [98]:
Correct = df[df['15AB_FPAct_3_'] == 'Correct']
Incorrect = df[df['15AB_FPAct_3_'] == 'Incorrect']

In [99]:
Incorrect[["Sub_class_New","15AB" ,"15AB_FPAct_3","Case"]].groupby(['Sub_class_New',"15AB","15AB_FPAct_3"]).count().reset_index()

   Sub_class_New                          15AB 15AB_FPAct_3  Case
0           AB01                MildFattyLiver         AB02    16
1           AB01                MildFattyLiver       Normal    13
2           AB02            ModerateFattyLiver         AB01    10
3           AB02            ModerateFattyLiver         AB03     9
4           AB02            ModerateFattyLiver       Normal     5
5           AB03              SevereFattyLiver         AB02    10
6           AB04                     Cirrhosis         AB06     1
7           AB04                     Cirrhosis         AB07     1
8           AB04                     Cirrhosis        AB081     1
9           AB04                     Cirrhosis       Normal     9
10          AB05                          PDF1        AB081     1
11          AB05                          PDF1       Normal     9
12          AB06                          PDF2         AB05     1
13          AB06                          PDF2         AB07     1
14          AB06                          PDF2       Normal     8
15          AB07                          PDF3       Normal    10
16         AB081                     Livermass         AB01     2
17         AB081                     Livermass         AB03     1
18         AB081                     Livermass       Normal    10
19         AB082                           BDD         AB05     1
20         AB082                           BDD        AB081     4
21         AB082                           BDD       Normal     7
22         AB083               LivermassAndBDD         AB04     1
23         AB083               LivermassAndBDD         AB05     1
24         AB083               LivermassAndBDD        AB082     4
25         AB083               LivermassAndBDD       Normal     2
26          AB09              Gallbladderstone         AB07     1
27          AB09              Gallbladderstone       Normal     4
28          AB10               GallbladderMass       Normal     1
29          AB10              Gallbladderpolyp       Normal     5
30          AB11                Hydronephrosis         AB12    11
31          AB11                Hydronephrosis       Normal     1
32          AB11                     RenalCyst       Normal     1
33          AB11                    RenalStone         AB12    12
34          AB11                    RenalStone       Normal     3
35          AB11  RenalstonesAndHydronephrosis         AB12     5
36          AB12                  Splenomegaly         AB04     4
37          AB12                  Splenomegaly         AB11     1
38          AB12                  Splenomegaly       Normal     4
39        Normal                        Normal         AB01     1
40        Normal                        Normal         AB04     1
41        Normal                        Normal         AB05     2

# แบบที่ 3 +FPPred

In [95]:
df

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,Spilt,15AB_FPPred_3,Prob_FPPred_3,15AB_pred,Prob_pred,15AB_FPAct_3,Prob_FPAct_3,15AB_pred_,15AB_FPPred_3_,15AB_FPAct_3_
0,0,AB01_40,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Test,Normal,0.413035,Normal,0.413035,Normal,0.413035,Incorrect,Incorrect,Incorrect
1,1,AB01_40,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Test,AB01,0.110668,AB01,0.110668,AB01,0.110668,Correct,Correct,Correct
2,2,AB01_40,P4,P41,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,Test,AB02,0.091490,AB02,0.091490,AB02,0.091490,Incorrect,Incorrect,Incorrect
3,3,AB01_40,P5,P51,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,2,MildFattyLiver,...,Test,AB01,0.075286,AB01,0.075286,AB01,0.075286,Correct,Correct,Correct
4,4,AB01_40,P3,P31,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,Test,AB02,0.065060,AB02,0.065060,AB02,0.065060,Incorrect,Incorrect,Incorrect
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,1307,350,P3,P32,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-B,2,Normal,...,Test,Normal,1.000000,Normal,1.000000,Normal,1.000000,Correct,Correct,Correct
1308,1308,350,P4,P42,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-B,2,Normal,...,Test,Normal,0.515819,Normal,0.515819,Normal,0.515819,Correct,Correct,Correct
1309,1309,350,P5,P52,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-C,2,Normal,...,Test,Normal,0.995000,Normal,0.995000,Normal,0.995000,Correct,Correct,Correct
1310,1310,350,P6,P61,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-C,2,Normal,...,Test,Normal,0.906968,Normal,0.906968,Normal,0.906968,Correct,Correct,Correct
1311,1311,350,P8,P8,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-E,2,Normal,...,Test,Normal,0.987972,Normal,0.987972,Normal,0.987972,Correct,Correct,Correct

In [96]:
Correct = df[df['15AB_FPPred_3_'] == 'Correct']
Incorrect = df[df['15AB_FPPred_3_'] == 'Incorrect']

In [97]:
Incorrect[["Sub_class_New","15AB" ,"15AB_FPPred_3","Case"]].groupby(['Sub_class_New',"15AB","15AB_FPPred_3"]).count().reset_index()

   Sub_class_New                          15AB 15AB_FPPred_3  Case
0           AB01                MildFattyLiver          AB02    16
1           AB01                MildFattyLiver        Normal    13
2           AB02            ModerateFattyLiver          AB01    10
3           AB02            ModerateFattyLiver          AB03     9
4           AB02            ModerateFattyLiver        Normal     5
5           AB03              SevereFattyLiver          AB02     9
6           AB03              SevereFattyLiver        Normal     1
7           AB04                     Cirrhosis          AB06     1
8           AB04                     Cirrhosis          AB07     1
9           AB04                     Cirrhosis         AB081     1
10          AB04                     Cirrhosis        Normal     9
11          AB05                          PDF1         AB081     1
12          AB05                          PDF1        Normal     9
13          AB06                          PDF2          AB05     1
14          AB06                          PDF2          AB07     2
15          AB06                          PDF2        Normal     8
16          AB07                          PDF3        Normal    10
17         AB081                     Livermass          AB01     2
18         AB081                     Livermass          AB03     1
19         AB081                     Livermass        Normal    10
20         AB082                           BDD          AB05     1
21         AB082                           BDD         AB081     4
22         AB082                           BDD          AB11     1
23         AB082                           BDD        Normal     7
24         AB083               LivermassAndBDD          AB04     1
25         AB083               LivermassAndBDD          AB05     1
26         AB083               LivermassAndBDD         AB082     4
27         AB083               LivermassAndBDD        Normal     2
28          AB09              Gallbladderstone          AB07     1
29          AB09              Gallbladderstone          AB12     1
30          AB09              Gallbladderstone        Normal     4
31          AB10               GallbladderMass        Normal     1
32          AB10              Gallbladderpolyp        Normal     5
33          AB11                Hydronephrosis          AB12    13
34          AB11                Hydronephrosis        Normal     1
35          AB11                     RenalCyst        Normal     1
36          AB11                    RenalStone          AB12    11
37          AB11                    RenalStone        Normal     3
38          AB11  RenalstonesAndHydronephrosis          AB12     5
39          AB12                  Splenomegaly          AB04     4
40          AB12                  Splenomegaly        Normal     4
41        Normal                        Normal          AB01     1
42        Normal                        Normal          AB04     1
43        Normal                        Normal          AB05     2

# รายเคส

In [158]:
import pandas as pd
df = pd.read_csv( '/home/yupaporn/CSV_file/result_BiTNet_FPScores.csv')#แก้

In [159]:
df

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,Spilt,15AB_FPPred_3,Prob_FPPred_3,15AB_pred,Prob_pred,15AB_FPAct_3,Prob_FPAct_3,15AB_pred_,15AB_FPPred_3_,15AB_FPAct_3_
0,0,AB01_40,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Test,Normal,0.413035,Normal,0.413035,Normal,0.413035,Incorrect,Incorrect,Incorrect
1,1,AB01_40,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Test,AB01,0.110668,AB01,0.110668,AB01,0.110668,Correct,Correct,Correct
2,2,AB01_40,P4,P41,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,Test,AB02,0.091490,AB02,0.091490,AB02,0.091490,Incorrect,Incorrect,Incorrect
3,3,AB01_40,P5,P51,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,2,MildFattyLiver,...,Test,AB01,0.075286,AB01,0.075286,AB01,0.075286,Correct,Correct,Correct
4,4,AB01_40,P3,P31,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,Test,AB02,0.065060,AB02,0.065060,AB02,0.065060,Incorrect,Incorrect,Incorrect
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,1307,350,P3,P32,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-B,2,Normal,...,Test,Normal,1.000000,Normal,1.000000,Normal,1.000000,Correct,Correct,Correct
1308,1308,350,P4,P42,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-B,2,Normal,...,Test,Normal,0.515819,Normal,0.515819,Normal,0.515819,Correct,Correct,Correct
1309,1309,350,P5,P52,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-C,2,Normal,...,Test,Normal,0.995000,Normal,0.995000,Normal,0.995000,Correct,Correct,Correct
1310,1310,350,P6,P61,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-C,2,Normal,...,Test,Normal,0.906968,Normal,0.906968,Normal,0.906968,Correct,Correct,Correct
1311,1311,350,P8,P8,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-E,2,Normal,...,Test,Normal,0.987972,Normal,0.987972,Normal,0.987972,Correct,Correct,Correct

In [160]:
df.columns

Index(['Unnamed: 0', 'Case', 'Abs Position', 'Sub Position', 'Class',
       'Path Full', 'Path Crop', 'Views', 'fold', '15AB', 'originalImage',
       'left', 'top', 'width', 'height', 'Rleft', 'Rtop', 'Rwidth', 'Rheight',
       'Sub_class_New', 'tag_AjNit', 'tag_AjWan', 'Test150', 'Spilt',
       '15AB_FPPred_3', 'Prob_FPPred_3', '15AB_pred', 'Prob_pred',
       '15AB_FPAct_3', 'Prob_FPAct_3', '15AB_pred_', '15AB_FPPred_3_',
       '15AB_FPAct_3_'],
      dtype='object')

### Abn&Normal

In [277]:
dff.columns

Index(['Unnamed: 0', 'Case', 'Abs Position', 'Sub Position', 'Class',
       'Path Full', 'Path Crop', 'Views', 'fold', '15AB', 'originalImage',
       'left', 'top', 'width', 'height', 'Rleft', 'Rtop', 'Rwidth', 'Rheight',
       'Sub_class_New', 'tag_AjNit', 'tag_AjWan', 'Test150', 'Spilt',
       '15AB_FPPred_3', 'Prob_FPPred_3', '15AB_pred', 'Prob_pred',
       '15AB_FPAct_3', 'Prob_FPAct_3', '15AB_pred_', '15AB_FPPred_3_',
       '15AB_FPAct_3_', 'Act_Predic_CCA', '15AB_pred_CCA', '15AB_FPAct_3_CCA',
       'AI_Pred_CCA', 'AI_Pred_CCAAct_3', 'Act_Predic_CCA_', '15AB_pred_CCA_',
       'Sub_class_New_'],
      dtype='object')

In [278]:
dff['Sub_class_New_'] = dff['Sub_class_New'].map({'AB12':1, 'AB04':1, 'AB06':1, 'Normal':0, 'AB081':1, 'AB10':1, 'AB03':1, 'AB02':1, 'AB083':1, 'AB11':1, 'AB01':1, 'AB09':1, 'AB07':1, 'AB082':1, 'AB05':1}).array
dff['15AB_pred_'] =  dff['15AB_pred'].map({'AB12':1, 'AB04':1, 'AB06':1, 'Normal':0, 'AB081':1, 'AB10':1, 'AB03':1, 'AB02':1, 'AB083':1, 'AB11':1, 'AB01':1, 'AB09':1, 'AB07':1, 'AB082':1, 'AB05':1}).array
dff['15AB_FPAct_3_'] =  dff['15AB_FPAct_3'].map({'AB12':1, 'AB04':1, 'AB06':1, 'Normal':0, 'AB081':1, 'AB10':1, 'AB03':1, 'AB02':1, 'AB083':1, 'AB11':1, 'AB01':1, 'AB09':1, 'AB07':1, 'AB082':1, 'AB05':1}).array

In [289]:
a = dff['Sub_class_New_'].tolist()
b = dff['15AB_pred_'].tolist()

res =[]
for  i in range(len(a)):
    if a[i] == b[i]:
        res.append('Correct')
    else:
        res.append('Incorrect')
dff['AI_Pred_AN']  = res

a = dff['Sub_class_New_'].tolist()
b = dff['15AB_FPAct_3_'].tolist()

res =[]
for  i in range(len(a)):
    if a[i] == b[i]:
        res.append('Correct')
    else:
        res.append('Incorrect')
dff['AI_Pred_ANAct_3']  = res

In [291]:
#Recall
#รายรูป#BiTNeT
Correct = dff[dff['AI_Pred_AN'] == 'Correct']
Incorrect = dff[dff['AI_Pred_AN'] == 'Incorrect']
Incorrect[["Sub_class_New_","15AB_pred_" ,"Unnamed: 0"]].groupby(['Sub_class_New_',"15AB_pred_"]).count().reset_index()

   Sub_class_New_  15AB_pred_  Unnamed: 0
0               0           1           5
1               1           0          92

In [292]:
#Recall
#รายรูป#BiTNeT+FP
Correct = dff[dff['AI_Pred_ANAct_3'] == 'Correct']
Incorrect = dff[dff['AI_Pred_ANAct_3'] == 'Incorrect']
Incorrect[["Sub_class_New_","15AB_FPAct_3_" ,"Unnamed: 0"]].groupby(['Sub_class_New_',"15AB_FPAct_3_"]).count().reset_index()

   Sub_class_New_  15AB_FPAct_3_  Unnamed: 0
0               0              1           4
1               1              0          92

In [296]:
len(dff[dff['Sub_class_New_']==0])

857

In [297]:
len(dff[dff['Sub_class_New_']!=0])

455

In [293]:
#Precision
#รายรูป#BiTNeT
dff[["15AB_pred_", "AI_Pred_AN", "Case"]].groupby(["15AB_pred_", "AI_Pred_AN"]).count().reset_index()

   15AB_pred_ AI_Pred_AN  Case
0           0    Correct   852
1           0  Incorrect    92
2           1    Correct   363
3           1  Incorrect     5

In [294]:
#Precision
#รายรูป#BiTNeT+FP
dff[["15AB_FPAct_3_", "AI_Pred_ANAct_3", "Case"]].groupby(["15AB_FPAct_3_", "AI_Pred_ANAct_3"]).count().reset_index()

   15AB_FPAct_3_ AI_Pred_ANAct_3  Case
0              0         Correct   853
1              0       Incorrect    92
2              1         Correct   363
3              1       Incorrect     4

In [266]:
col_name = ['Case', 'AN_Case_Act', 'AN_Case_AI','AN_Case_AIAct_3', 'Set_Case_AI' ,'Set_Case_AIAct_3', 'Set_Case_Act', 'Num_Case']
dff2 = pd.DataFrame(columns = col_name)

case = list(set(df['Case']))
AN_15AB_case = []
num_case = []
set_case = []
for i in case:
    cas = set(df[df['Case'] == i]['15AB_pred'])
    set_case.append(list(cas))
    num_case.append(len(cas))
    if cas == {'Normal'}:
        AN_15AB_case.append('Normal')
        # print(cas)
    else:
        AN_15AB_case.append('Abnormal')
dff2['AN_Case_AI'] = AN_15AB_case
dff2['Case'] = case
dff2['Num_Case'] = num_case
dff2['Set_Case_AI'] = set_case

case = list(set(df['Case']))
AN_15AB_case = []
set_case = []
for i in case:
    cas = set(df[df['Case'] == i]['Sub_class_New'])
    set_case.append(list(cas))
    if cas == {'Normal'}:
        AN_15AB_case.append('Normal')
        # print(cas)
    else:
        AN_15AB_case.append('Abnormal')
dff2['AN_Case_Act'] = AN_15AB_case
dff2['Set_Case_Act'] = set_case

In [267]:
case = list(set(df['Case']))
AN_15AB_case = []
num_case = []
set_case = []
for i in case:
    cas = set(df[df['Case'] == i]['15AB_FPAct_3'])
    set_case.append(list(cas))
    num_case.append(len(cas))
    if cas == {'Normal'}:
        AN_15AB_case.append('Normal')
        # print(cas)
    else:
        AN_15AB_case.append('Abnormal')
dff2['AN_Case_AIAct_3'] = AN_15AB_case
dff2['Set_Case_AIAct_3'] = set_case

In [268]:
dff2

,Case,AN_Case_Act,AN_Case_AI,AN_Case_AIAct_3,Set_Case_AI,Set_Case_AIAct_3,Set_Case_Act,Num_Case
0,1,Normal,Normal,Normal,[Normal],[Normal],[Normal],1
1,AB081_65,Abnormal,Abnormal,Abnormal,[AB081],[AB081],[AB081],1
2,AB02_30,Abnormal,Abnormal,Abnormal,"[AB02, Normal]","[AB02, Normal]",[AB02],2
3,AB10_9,Abnormal,Abnormal,Abnormal,[AB10],[AB10],[AB10],1
4,AB02_90,Abnormal,Abnormal,Abnormal,[AB03],[AB03],[AB02],1
...,...,...,...,...,...,...,...,...
368,Ab3_136,Abnormal,Abnormal,Abnormal,[AB02],[AB02],[AB03],1
369,150,Normal,Normal,Normal,[Normal],[Normal],[Normal],1
370,AB09_101,Abnormal,Abnormal,Abnormal,[AB07],[AB07],[AB09],1
371,AB05_2,Abnormal,Normal,Normal,[Normal],[Normal],[AB05],1
372,141,Normal,Normal,Normal,[Normal],[Normal],[Normal],1

In [269]:
a = dff2['AN_Case_Act'].tolist()
b = dff2['AN_Case_AI'].tolist()

res =[]
for  i in range(len(a)):
    if a[i] == b[i]:
        res.append('Correct')
    else:
        res.append('Incorrect')
dff2['AI_Pred_AN']  = res

a = dff2['AN_Case_Act'].tolist()
b = dff2['AN_Case_AIAct_3'].tolist()

res =[]
for  i in range(len(a)):
    if a[i] == b[i]:
        res.append('Correct')
    else:
        res.append('Incorrect')
dff2['AI_Pred_ANAct_3']  = res

In [270]:
dff2

,Case,AN_Case_Act,AN_Case_AI,AN_Case_AIAct_3,Set_Case_AI,Set_Case_AIAct_3,Set_Case_Act,Num_Case,AI_Pred_AN,AI_Pred_ANAct_3
0,1,Normal,Normal,Normal,[Normal],[Normal],[Normal],1,Correct,Correct
1,AB081_65,Abnormal,Abnormal,Abnormal,[AB081],[AB081],[AB081],1,Correct,Correct
2,AB02_30,Abnormal,Abnormal,Abnormal,"[AB02, Normal]","[AB02, Normal]",[AB02],2,Correct,Correct
3,AB10_9,Abnormal,Abnormal,Abnormal,[AB10],[AB10],[AB10],1,Correct,Correct
4,AB02_90,Abnormal,Abnormal,Abnormal,[AB03],[AB03],[AB02],1,Correct,Correct
...,...,...,...,...,...,...,...,...,...,...
368,Ab3_136,Abnormal,Abnormal,Abnormal,[AB02],[AB02],[AB03],1,Correct,Correct
369,150,Normal,Normal,Normal,[Normal],[Normal],[Normal],1,Correct,Correct
370,AB09_101,Abnormal,Abnormal,Abnormal,[AB07],[AB07],[AB09],1,Correct,Correct
371,AB05_2,Abnormal,Normal,Normal,[Normal],[Normal],[AB05],1,Incorrect,Incorrect
372,141,Normal,Normal,Normal,[Normal],[Normal],[Normal],1,Correct,Correct

#### Recall

In [74]:
#BiTNeT
Correct = dff2[dff2['AI_Pred_AN'] == 'Correct']
Incorrect = dff2[dff2['AI_Pred_AN'] == 'Incorrect']
Incorrect[["AN_Case_Act","AN_Case_AI" ,"Case"]].groupby(['AN_Case_Act',"AN_Case_AI"]).count().reset_index()

  AN_Case_Act AN_Case_AI  Case
0    Abnormal     Normal    50
1      Normal   Abnormal     4

In [75]:
#BiTNeT+5FP_3
Correct = dff2[dff2['AI_Pred_ANAct_3'] == 'Correct']
Incorrect = dff2[dff2['AI_Pred_ANAct_3'] == 'Incorrect']
Incorrect[["AN_Case_Act","AN_Case_AIAct_3" ,"Case"]].groupby(['AN_Case_Act',"AN_Case_AIAct_3"]).count().reset_index()

  AN_Case_Act AN_Case_AIAct_3  Case
0    Abnormal          Normal    50
1      Normal        Abnormal     3

In [83]:
len(set(dff2[dff2['AN_Case_Act'] == 'Normal']['Case']))

71

In [84]:
len(set(dff2[dff2['AN_Case_Act'] == 'Abnormal']['Case']))

302

In [86]:
train_df = pd.read_csv( '/home/yupaporn/codes/USAI/Traindf.csv')

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Case', 'Abs Position', 'Sub Position',
       'Class', 'Sub_class', 'Path Full', 'Path Crop', 'Views', 'fold',
       'tagName', 'originalImage', 'left', 'top', 'width', 'height', 'Rleft',
       'Rtop', 'Rwidth', 'Rheight', 'filename'],
      dtype='object')

In [91]:
len(set(train_df[train_df['Sub_class']== 'Normal']['Case']))

289

In [92]:
train_df[train_df['Sub_class']!= 'Normal']['Case']

0        15
1        15
2        15
3        15
4        15
       ...
1818    326
1819    330
1820    331
1821    358
1822    373
Name: Case, Length: 1823, dtype: int64

#### Precision

In [77]:
#BiTNeT
dff2[["AN_Case_AI", "AI_Pred_AN", "Case"]].groupby(["AN_Case_AI", "AI_Pred_AN"]).count().reset_index()

  AN_Case_AI AI_Pred_AN  Case
0   Abnormal    Correct   252
1   Abnormal  Incorrect     4
2     Normal    Correct    67
3     Normal  Incorrect    50

In [78]:
#BiTNeT+5FP_3
dff2[["AN_Case_AIAct_3", "AI_Pred_ANAct_3", "Case"]].groupby(["AN_Case_AIAct_3", "AI_Pred_ANAct_3"]).count().reset_index()

  AN_Case_AIAct_3 AI_Pred_ANAct_3  Case
0        Abnormal         Correct   252
1        Abnormal       Incorrect     3
2          Normal         Correct    68
3          Normal       Incorrect    50

### Suspect&Non-Suspect

In [233]:
Suspected_CCA = ['AB05', 'AB06', 'AB07', 'AB081', 'AB082', 'AB083']

In [234]:
dff = df

In [235]:
dff.columns

Index(['Unnamed: 0', 'Case', 'Abs Position', 'Sub Position', 'Class',
       'Path Full', 'Path Crop', 'Views', 'fold', '15AB', 'originalImage',
       'left', 'top', 'width', 'height', 'Rleft', 'Rtop', 'Rwidth', 'Rheight',
       'Sub_class_New', 'tag_AjNit', 'tag_AjWan', 'Test150', 'Spilt',
       '15AB_FPPred_3', 'Prob_FPPred_3', '15AB_pred', 'Prob_pred',
       '15AB_FPAct_3', 'Prob_FPAct_3', '15AB_pred_', '15AB_FPPred_3_',
       '15AB_FPAct_3_', 'Act_Predic_CCA', '15AB_pred_CCA', '15AB_FPAct_3_CCA',
       'AI_Pred_CCA', 'AI_Pred_CCAAct_3'],
      dtype='object')

In [236]:
a_ = dff['Sub_class_New'].tolist()
Act_Predic =[]
for  i in range(len(a_)):
    if a_[i] in Suspected_CCA:
        a = 'SuspectedCCA'
        Act_Predic.append(a)
    else:
        a = 'Non_SuspectedCCA'
        Act_Predic.append(a) 

dff['Act_Predic_CCA'] = Act_Predic

In [237]:
a_ = dff['15AB_pred'].tolist()
AI_Predic =[]
for  i in range(len(a_)):
    if a_[i] in Suspected_CCA:
        a = 'SuspectedCCA'
        AI_Predic.append(a)
    else:
        a = 'Non_SuspectedCCA'
        AI_Predic.append(a)
        
dff['15AB_pred_CCA'] = AI_Predic        

a_ = dff['15AB_FPAct_3'].tolist()
AI_Predic =[]
for  i in range(len(a_)):
    if a_[i] in Suspected_CCA:
        a = 'SuspectedCCA'
        AI_Predic.append(a)
    else:
        a = 'Non_SuspectedCCA'
        AI_Predic.append(a)
        
dff['15AB_FPAct_3_CCA'] = AI_Predic

In [238]:
dff.head()

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,15AB_FPAct_3,Prob_FPAct_3,15AB_pred_,15AB_FPPred_3_,15AB_FPAct_3_,Act_Predic_CCA,15AB_pred_CCA,15AB_FPAct_3_CCA,AI_Pred_CCA,AI_Pred_CCAAct_3
0,0,AB01_40,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Normal,0.413035,Incorrect,Incorrect,Incorrect,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Incorrect,Incorrect
1,1,AB01_40,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,AB01,0.110668,Correct,Correct,Correct,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
2,2,AB01_40,P4,P41,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,AB02,0.091490,Incorrect,Incorrect,Incorrect,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
3,3,AB01_40,P5,P51,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,2,MildFattyLiver,...,AB01,0.075286,Correct,Correct,Correct,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
4,4,AB01_40,P3,P31,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,AB02,0.065060,Incorrect,Incorrect,Incorrect,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct

In [239]:
a = dff['Act_Predic_CCA'].tolist()
b = dff['15AB_pred_CCA'].tolist()

res =[]
for  i in range(len(a)):
    if a[i] == b[i]:
        res.append('Correct')
    else:
        res.append('Incorrect')
dff['AI_Pred_CCA']  = res

a = dff['Act_Predic_CCA'].tolist()
b = dff['15AB_FPAct_3_CCA'].tolist()

res =[]
for  i in range(len(a)):
    if a[i] == b[i]:
        res.append('Correct')
    else:
        res.append('Incorrect')
dff['AI_Pred_CCAAct_3']  = res

In [243]:
#Recall
#รายรูป#BiTNeT
Correct = dff[dff['AI_Pred_CCA'] == 'Correct']
Incorrect = dff[dff['AI_Pred_CCA'] == 'Incorrect']
Incorrect[["Act_Predic_CCA","15AB_pred_CCA" ,"Unnamed: 0"]].groupby(['Act_Predic_CCA',"15AB_pred_CCA"]).count().reset_index()

     Act_Predic_CCA     15AB_pred_CCA  Unnamed: 0
0  Non_SuspectedCCA      SuspectedCCA           6
1      SuspectedCCA  Non_SuspectedCCA          52

In [242]:
#Recall
#รายรูป#BiTNeT+FP
Correct = dff[dff['AI_Pred_CCAAct_3'] == 'Correct']
Incorrect = dff[dff['AI_Pred_CCAAct_3'] == 'Incorrect']
Incorrect[["Act_Predic_CCA","15AB_FPAct_3_CCA" ,"Unnamed: 0"]].groupby(['Act_Predic_CCA',"15AB_FPAct_3_CCA"]).count().reset_index()

     Act_Predic_CCA  15AB_FPAct_3_CCA  Unnamed: 0
0  Non_SuspectedCCA      SuspectedCCA           6
1      SuspectedCCA  Non_SuspectedCCA          50

In [244]:
dff

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,15AB_FPAct_3,Prob_FPAct_3,15AB_pred_,15AB_FPPred_3_,15AB_FPAct_3_,Act_Predic_CCA,15AB_pred_CCA,15AB_FPAct_3_CCA,AI_Pred_CCA,AI_Pred_CCAAct_3
0,0,AB01_40,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Normal,0.413035,Incorrect,Incorrect,Incorrect,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
1,1,AB01_40,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,AB01,0.110668,Correct,Correct,Correct,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
2,2,AB01_40,P4,P41,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,AB02,0.091490,Incorrect,Incorrect,Incorrect,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
3,3,AB01_40,P5,P51,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,2,MildFattyLiver,...,AB01,0.075286,Correct,Correct,Correct,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
4,4,AB01_40,P3,P31,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,AB02,0.065060,Incorrect,Incorrect,Incorrect,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,1307,350,P3,P32,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-B,2,Normal,...,Normal,1.000000,Correct,Correct,Correct,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
1308,1308,350,P4,P42,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-B,2,Normal,...,Normal,0.515819,Correct,Correct,Correct,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
1309,1309,350,P5,P52,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-C,2,Normal,...,Normal,0.995000,Correct,Correct,Correct,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
1310,1310,350,P6,P61,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-C,2,Normal,...,Normal,0.906968,Correct,Correct,Correct,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
1311,1311,350,P8,P8,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-E,2,Normal,...,Normal,0.987972,Correct,Correct,Correct,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct

In [245]:
#Precision
#รายรูป#BiTNeT
dff[["15AB_pred_CCA", "AI_Pred_CCA", "Case"]].groupby(["15AB_pred_CCA", "AI_Pred_CCA"]).count().reset_index()

      15AB_pred_CCA AI_Pred_CCA  Case
0  Non_SuspectedCCA     Correct  1164
1  Non_SuspectedCCA   Incorrect    52
2      SuspectedCCA     Correct    90
3      SuspectedCCA   Incorrect     6

In [246]:
#Precision
#รายรูป#BiTNeT+FP
dff[["15AB_FPAct_3_CCA", "AI_Pred_CCAAct_3", "Case"]].groupby(["15AB_FPAct_3_CCA", "AI_Pred_CCAAct_3"]).count().reset_index()

   15AB_FPAct_3_CCA AI_Pred_CCAAct_3  Case
0  Non_SuspectedCCA          Correct  1164
1  Non_SuspectedCCA        Incorrect    50
2      SuspectedCCA          Correct    92
3      SuspectedCCA        Incorrect     6

In [177]:
dff.columns

Index(['Unnamed: 0', 'Case', 'Abs Position', 'Sub Position', 'Class',
       'Path Full', 'Path Crop', 'Views', 'fold', '15AB', 'originalImage',
       'left', 'top', 'width', 'height', 'Rleft', 'Rtop', 'Rwidth', 'Rheight',
       'Sub_class_New', 'tag_AjNit', 'tag_AjWan', 'Test150', 'Spilt',
       '15AB_FPPred_3', 'Prob_FPPred_3', '15AB_pred', 'Prob_pred',
       '15AB_FPAct_3', 'Prob_FPAct_3', '15AB_pred_', '15AB_FPPred_3_',
       '15AB_FPAct_3_', 'Act_Predic_CCA', '15AB_pred_CCA', '15AB_FPAct_3_CCA',
       'AI_Pred_CCA', 'AI_Pred_CCAAct_3'],
      dtype='object')

In [178]:
len(dff[dff['Act_Predic_CCA']=='SuspectedCCA'])

142

In [179]:
len(dff[dff['Act_Predic_CCA']!='SuspectedCCA'])

1170

In [180]:
col_name = ['Case', 'CCA_Case_Act', 'CCA_Case_AI','CCA_Case_AIAct_3']
dff2 = pd.DataFrame(columns = col_name)

case = list(set(dff['Case']))
result_pre = []
# set_case = []

for i in range(len(case)):
    a = dff[dff['Case'] ==case[i]]
    res_ = set(a['Act_Predic_CCA'])
    if len(res_) == 1:
        m = a['Act_Predic_CCA'].tolist()
        aa = m[0]
        result_pre.append(aa)
    elif res_ =={'Non_SuspectedCCA', 'SuspectedCCA'}:
        aa = 'SuspectedCCA'
        result_pre.append(aa)
dff2['CCA_Case_Act'] = result_pre
        
case = list(set(dff['Case']))
result_pre = []
for i in range(len(case)):
    a = dff[dff['Case'] ==case[i]]
    res_ = set(a['15AB_pred_CCA'])
    if len(res_) == 1:
        m = a['15AB_pred_CCA'].tolist()
        aa = m[0]
        result_pre.append(aa)
    elif res_ =={'Non_SuspectedCCA', 'SuspectedCCA'}:
        aa = 'SuspectedCCA'
        result_pre.append(aa)
dff2['CCA_Case_AI'] = result_pre
        
result_pre = []
for i in range(len(case)):
    a = dff[dff['Case'] ==case[i]]
    res_ = set(a['15AB_FPAct_3_CCA'])
    if len(res_) == 1:
        m = a['15AB_FPAct_3_CCA'].tolist()
        aa = m[0]
        result_pre.append(aa)
    elif res_ =={'Non_SuspectedCCA', 'SuspectedCCA'}:
        aa = 'SuspectedCCA'
        result_pre.append(aa)
dff2['CCA_Case_AIAct_3'] = result_pre
dff2['Case'] = case

In [181]:
dff2

         Case      CCA_Case_Act       CCA_Case_AI  CCA_Case_AIAct_3
0           1  Non_SuspectedCCA  Non_SuspectedCCA  Non_SuspectedCCA
1    AB081_65      SuspectedCCA      SuspectedCCA      SuspectedCCA
2     AB02_30  Non_SuspectedCCA  Non_SuspectedCCA  Non_SuspectedCCA
3      AB10_9  Non_SuspectedCCA  Non_SuspectedCCA  Non_SuspectedCCA
4     AB02_90  Non_SuspectedCCA  Non_SuspectedCCA  Non_SuspectedCCA
..        ...               ...               ...               ...
368   Ab3_136  Non_SuspectedCCA  Non_SuspectedCCA  Non_SuspectedCCA
369       150  Non_SuspectedCCA  Non_SuspectedCCA  Non_SuspectedCCA
370  AB09_101  Non_SuspectedCCA      SuspectedCCA      SuspectedCCA
371    AB05_2      SuspectedCCA  Non_SuspectedCCA  Non_SuspectedCCA
372       141  Non_SuspectedCCA  Non_SuspectedCCA  Non_SuspectedCCA

[373 rows x 4 columns]

In [182]:
a = dff2['CCA_Case_Act'].tolist()
b = dff2['CCA_Case_AI'].tolist()

res =[]
for  i in range(len(a)):
    if a[i] == b[i]:
        res.append('Correct')
    else:
        res.append('Incorrect')
dff2['AI_Pred_CCA']  = res

a = dff2['CCA_Case_Act'].tolist()
b = dff2['CCA_Case_AIAct_3'].tolist()

res =[]
for  i in range(len(a)):
    if a[i] == b[i]:
        res.append('Correct')
    else:
        res.append('Incorrect')
dff2['AI_Pred_CCAAct_3']  = res

In [183]:
dff2

,Case,CCA_Case_Act,CCA_Case_AI,CCA_Case_AIAct_3,AI_Pred_CCA,AI_Pred_CCAAct_3
0,1,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
1,AB081_65,SuspectedCCA,SuspectedCCA,SuspectedCCA,Correct,Correct
2,AB02_30,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
3,AB10_9,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
4,AB02_90,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
...,...,...,...,...,...,...
368,Ab3_136,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
369,150,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
370,AB09_101,Non_SuspectedCCA,SuspectedCCA,SuspectedCCA,Incorrect,Incorrect
371,AB05_2,SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Incorrect,Incorrect
372,141,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct

#### Recall

In [184]:
#BiTNeT
Correct = dff2[dff2['AI_Pred_CCA'] == 'Correct']
Incorrect = dff2[dff2['AI_Pred_CCA'] == 'Incorrect']
Incorrect[["CCA_Case_Act","CCA_Case_AI" ,"Case"]].groupby(['CCA_Case_Act',"CCA_Case_AI"]).count().reset_index()

       CCA_Case_Act       CCA_Case_AI  Case
0  Non_SuspectedCCA      SuspectedCCA     5
1      SuspectedCCA  Non_SuspectedCCA    35

In [185]:
#BiTNeT+FP
Correct = dff2[dff2['AI_Pred_CCAAct_3'] == 'Correct']
Incorrect = dff2[dff2['AI_Pred_CCAAct_3'] == 'Incorrect']
Incorrect[["CCA_Case_Act","CCA_Case_AIAct_3" ,"Case"]].groupby(['CCA_Case_Act',"CCA_Case_AIAct_3"]).count().reset_index()

       CCA_Case_Act  CCA_Case_AIAct_3  Case
0  Non_SuspectedCCA      SuspectedCCA     5
1      SuspectedCCA  Non_SuspectedCCA    33

#### Precision

In [186]:
#BiTNeT
dff2[["CCA_Case_AI", "AI_Pred_CCA", "Case"]].groupby(["CCA_Case_AI", "AI_Pred_CCA"]).count().reset_index()

        CCA_Case_AI AI_Pred_CCA  Case
0  Non_SuspectedCCA     Correct   254
1  Non_SuspectedCCA   Incorrect    35
2      SuspectedCCA     Correct    79
3      SuspectedCCA   Incorrect     5

In [187]:
#BiTNeT+FP
dff2[["CCA_Case_AI", "AI_Pred_CCAAct_3", "Case"]].groupby(["CCA_Case_AI", "AI_Pred_CCAAct_3"]).count().reset_index()

        CCA_Case_AI AI_Pred_CCAAct_3  Case
0  Non_SuspectedCCA          Correct   256
1  Non_SuspectedCCA        Incorrect    33
2      SuspectedCCA          Correct    79
3      SuspectedCCA        Incorrect     5

In [188]:
len(set(dff2[dff2['CCA_Case_Act'] == 'SuspectedCCA']['Case']))

114

In [189]:
len(set(dff2[dff2['CCA_Case_Act'] != 'SuspectedCCA']['Case']))

259

In [190]:
259+114

373

## Suspect , Non-Suspect and Normal

In [247]:
Suspected_CCA = ['AB05', 'AB06', 'AB07', 'AB081', 'AB082', 'AB083']

In [248]:
Normal = ['Normal']

In [249]:
dff = df

In [250]:
dff.columns

Index(['Unnamed: 0', 'Case', 'Abs Position', 'Sub Position', 'Class',
       'Path Full', 'Path Crop', 'Views', 'fold', '15AB', 'originalImage',
       'left', 'top', 'width', 'height', 'Rleft', 'Rtop', 'Rwidth', 'Rheight',
       'Sub_class_New', 'tag_AjNit', 'tag_AjWan', 'Test150', 'Spilt',
       '15AB_FPPred_3', 'Prob_FPPred_3', '15AB_pred', 'Prob_pred',
       '15AB_FPAct_3', 'Prob_FPAct_3', '15AB_pred_', '15AB_FPPred_3_',
       '15AB_FPAct_3_', 'Act_Predic_CCA', '15AB_pred_CCA', '15AB_FPAct_3_CCA',
       'AI_Pred_CCA', 'AI_Pred_CCAAct_3'],
      dtype='object')

In [251]:
a_ = dff['Sub_class_New'].tolist()
Act_Predic =[]
for  i in range(len(a_)):
    if a_[i] in Suspected_CCA:
        a = 'SuspectedCCA'
        Act_Predic.append(a)
    elif a_[i] in Normal:
        a = 'Normal'
        Act_Predic.append(a)
    else:
        a = 'Non_SuspectedCCA'
        Act_Predic.append(a) 

dff['Act_Predic_CCA'] = Act_Predic

In [252]:
a_ = dff['15AB_pred'].tolist()
AI_Predic =[]
for  i in range(len(a_)):
    if a_[i] in Suspected_CCA:
        a = 'SuspectedCCA'
        AI_Predic.append(a)
    elif a_[i] in Normal:
        a = 'Normal'
        AI_Predic.append(a)
    else:
        a = 'Non_SuspectedCCA'
        AI_Predic.append(a) 
        
dff['15AB_pred_CCA'] = AI_Predic        

a_ = dff['15AB_FPAct_3'].tolist()
AI_Predic =[]
for  i in range(len(a_)):
    if a_[i] in Suspected_CCA:
        a = 'SuspectedCCA'
        AI_Predic.append(a)
    elif a_[i] in Normal:
        a = 'Normal'
        AI_Predic.append(a)
    else:
        a = 'Non_SuspectedCCA'
        AI_Predic.append(a) 
        
dff['15AB_FPAct_3_CCA'] = AI_Predic

In [253]:
set(dff['15AB_FPAct_3_CCA'])

{'Non_SuspectedCCA', 'Normal', 'SuspectedCCA'}

In [254]:
dff.head()

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,15AB_FPAct_3,Prob_FPAct_3,15AB_pred_,15AB_FPPred_3_,15AB_FPAct_3_,Act_Predic_CCA,15AB_pred_CCA,15AB_FPAct_3_CCA,AI_Pred_CCA,AI_Pred_CCAAct_3
0,0,AB01_40,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Normal,0.413035,Incorrect,Incorrect,Incorrect,Non_SuspectedCCA,Normal,Normal,Correct,Correct
1,1,AB01_40,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,AB01,0.110668,Correct,Correct,Correct,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
2,2,AB01_40,P4,P41,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,AB02,0.091490,Incorrect,Incorrect,Incorrect,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
3,3,AB01_40,P5,P51,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,2,MildFattyLiver,...,AB01,0.075286,Correct,Correct,Correct,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
4,4,AB01_40,P3,P31,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,AB02,0.065060,Incorrect,Incorrect,Incorrect,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct

In [255]:
a = dff['Act_Predic_CCA'].tolist()
b = dff['15AB_pred_CCA'].tolist()

res =[]
for  i in range(len(a)):
    if a[i] == b[i]:
        res.append('Correct')
    else:
        res.append('Incorrect')
dff['AI_Pred_CCA']  = res

a = dff['Act_Predic_CCA'].tolist()
b = dff['15AB_FPAct_3_CCA'].tolist()

res =[]
for  i in range(len(a)):
    if a[i] == b[i]:
        res.append('Correct')
    else:
        res.append('Incorrect')
dff['AI_Pred_CCAAct_3']  = res

In [256]:
dff.head()

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,15AB_FPAct_3,Prob_FPAct_3,15AB_pred_,15AB_FPPred_3_,15AB_FPAct_3_,Act_Predic_CCA,15AB_pred_CCA,15AB_FPAct_3_CCA,AI_Pred_CCA,AI_Pred_CCAAct_3
0,0,AB01_40,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Normal,0.413035,Incorrect,Incorrect,Incorrect,Non_SuspectedCCA,Normal,Normal,Incorrect,Incorrect
1,1,AB01_40,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,AB01,0.110668,Correct,Correct,Correct,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
2,2,AB01_40,P4,P41,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,AB02,0.091490,Incorrect,Incorrect,Incorrect,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
3,3,AB01_40,P5,P51,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,2,MildFattyLiver,...,AB01,0.075286,Correct,Correct,Correct,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
4,4,AB01_40,P3,P31,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,AB02,0.065060,Incorrect,Incorrect,Incorrect,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct

In [257]:
#Recall
#รายรูป#BiTNeT
Correct = dff[dff['AI_Pred_CCA'] == 'Correct']
Incorrect = dff[dff['AI_Pred_CCA'] == 'Incorrect']
Incorrect[["Act_Predic_CCA","15AB_pred_CCA" ,"Case"]].groupby(['Act_Predic_CCA',"15AB_pred_CCA"]).count().reset_index()

     Act_Predic_CCA     15AB_pred_CCA  Case
0  Non_SuspectedCCA            Normal    46
1  Non_SuspectedCCA      SuspectedCCA     4
2            Normal  Non_SuspectedCCA     3
3            Normal      SuspectedCCA     2
4      SuspectedCCA  Non_SuspectedCCA     6
5      SuspectedCCA            Normal    46

In [258]:
#Recall
#รายรูป#BiTNeT+แบบที่3
Correct = dff[dff['AI_Pred_CCAAct_3'] == 'Correct']
Incorrect = dff[dff['AI_Pred_CCAAct_3'] == 'Incorrect']
Incorrect[["Act_Predic_CCA","15AB_FPAct_3_CCA" ,"Case"]].groupby(['Act_Predic_CCA',"15AB_FPAct_3_CCA"]).count().reset_index()

     Act_Predic_CCA  15AB_FPAct_3_CCA  Case
0  Non_SuspectedCCA            Normal    46
1  Non_SuspectedCCA      SuspectedCCA     4
2            Normal  Non_SuspectedCCA     2
3            Normal      SuspectedCCA     2
4      SuspectedCCA  Non_SuspectedCCA     4
5      SuspectedCCA            Normal    46

In [260]:
len(dff[dff['Act_Predic_CCA']=='SuspectedCCA'])

142

In [261]:
len(dff[dff['Act_Predic_CCA']=='Non_SuspectedCCA'])

313

In [262]:
len(dff[dff['Act_Predic_CCA']=='Normal'])

857

In [263]:
dff

,Unnamed: 0,Case,Abs Position,Sub Position,Class,Path Full,Path Crop,Views,fold,15AB,...,15AB_FPAct_3,Prob_FPAct_3,15AB_pred_,15AB_FPPred_3_,15AB_FPAct_3_,Act_Predic_CCA,15AB_pred_CCA,15AB_FPAct_3_CCA,AI_Pred_CCA,AI_Pred_CCAAct_3
0,0,AB01_40,P1,P1,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,Normal,0.413035,Incorrect,Incorrect,Incorrect,Non_SuspectedCCA,Normal,Normal,Incorrect,Incorrect
1,1,AB01_40,P2,P2,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-A,2,MildFattyLiver,...,AB01,0.110668,Correct,Correct,Correct,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
2,2,AB01_40,P4,P41,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,AB02,0.091490,Incorrect,Incorrect,Incorrect,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
3,3,AB01_40,P5,P51,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-C,2,MildFattyLiver,...,AB01,0.075286,Correct,Correct,Correct,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
4,4,AB01_40,P3,P31,Abnormal,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,/media/tohn/HDD/VISION_dataset/USAI/ABnormal01...,FP-B,2,MildFattyLiver,...,AB02,0.065060,Incorrect,Incorrect,Incorrect,Non_SuspectedCCA,Non_SuspectedCCA,Non_SuspectedCCA,Correct,Correct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,1307,350,P3,P32,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-B,2,Normal,...,Normal,1.000000,Correct,Correct,Correct,Normal,Normal,Normal,Correct,Correct
1308,1308,350,P4,P42,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-B,2,Normal,...,Normal,0.515819,Correct,Correct,Correct,Normal,Normal,Normal,Correct,Correct
1309,1309,350,P5,P52,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-C,2,Normal,...,Normal,0.995000,Correct,Correct,Correct,Normal,Normal,Normal,Correct,Correct
1310,1310,350,P6,P61,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-C,2,Normal,...,Normal,0.906968,Correct,Correct,Correct,Normal,Normal,Normal,Correct,Correct
1311,1311,350,P8,P8,Normal,/media/tohn/HDD/VISION_dataset/USAI/US images ...,/media/tohn/HDD/VISION_dataset/USAI/US images ...,FP-E,2,Normal,...,Normal,0.987972,Correct,Correct,Correct,Normal,Normal,Normal,Correct,Correct

In [264]:
#Precision
#รายรูป#BiTNeT
dff[["15AB_pred_CCA", "AI_Pred_CCA", "Case"]].groupby(["15AB_pred_CCA", "AI_Pred_CCA"]).count().reset_index()

      15AB_pred_CCA AI_Pred_CCA  Case
0  Non_SuspectedCCA     Correct   263
1  Non_SuspectedCCA   Incorrect     9
2            Normal     Correct   852
3            Normal   Incorrect    92
4      SuspectedCCA     Correct    90
5      SuspectedCCA   Incorrect     6

In [265]:
#Precision
#รายรูป#BiTNeT+แบบที่3
dff[["15AB_FPAct_3_CCA", "AI_Pred_CCAAct_3", "Case"]].groupby(["15AB_FPAct_3_CCA", "AI_Pred_CCAAct_3"]).count().reset_index()

   15AB_FPAct_3_CCA AI_Pred_CCAAct_3  Case
0  Non_SuspectedCCA          Correct   263
1  Non_SuspectedCCA        Incorrect     6
2            Normal          Correct   853
3            Normal        Incorrect    92
4      SuspectedCCA          Correct    92
5      SuspectedCCA        Incorrect     6

In [ ]:
dff

In [146]:
col_name = ['Case', 'CCA_Case_Act', 'CCA_Case_AI','CCA_Case_AIAct_3']
dff2 = pd.DataFrame(columns = col_name)

case = list(set(dff['Case']))
result_pre = []
# set_case = []

for i in range(len(case)):
    a = dff[dff['Case'] ==case[i]]
    res_ = set(a['Act_Predic_CCA'])
    if len(res_) == 1:
        m = a['Act_Predic_CCA'].tolist()
        aa = m[0]
        result_pre.append(aa)
    elif  res_ =={'Non_SuspectedCCA', 'SuspectedCCA'}:
        aa = 'SuspectedCCA'
        result_pre.append(aa)
    elif  res_ =={'Normal', 'SuspectedCCA'}:
        aa = 'SuspectedCCA'
        result_pre.append(aa)
    elif  res_ =={'Non_SuspectedCCA', 'Normal'}:
        aa = 'Non_SuspectedCCA'
        result_pre.append(aa)
    elif res_ =={'Non_SuspectedCCA', 'Normal', 'SuspectedCCA'}:
        aa = 'SuspectedCCA'
        result_pre.append(aa)
        
dff2['CCA_Case_Act'] = result_pre

In [147]:
case = list(set(dff['Case']))
result_pre = []
for i in range(len(case)):
    a = dff[dff['Case'] ==case[i]]
    res_ = set(a['15AB_pred_CCA'])
#     result_pre.append(res_)
    if len(res_) == 1:
        m = a['15AB_pred_CCA'].tolist()
        aa = m[0]
        result_pre.append(aa)
    elif  res_ =={'Non_SuspectedCCA', 'SuspectedCCA'}:
        aa = 'SuspectedCCA'
        result_pre.append(aa)
    elif  res_ =={'Normal', 'SuspectedCCA'}:
        aa = 'SuspectedCCA'
        result_pre.append(aa)
    elif  res_ =={'Non_SuspectedCCA', 'Normal'}:
        aa = 'Non_SuspectedCCA'
        result_pre.append(aa)
    elif res_ =={'Non_SuspectedCCA', 'Normal', 'SuspectedCCA'}:
        aa = 'SuspectedCCA'
        result_pre.append(aa)
        
dff2['CCA_Case_AI'] = result_pre

In [148]:
result_pre = []
for i in range(len(case)):
    a = dff[dff['Case'] ==case[i]]
    res_ = set(a['15AB_FPAct_3_CCA'])
    if len(res_) == 1:
        m = a['15AB_FPAct_3_CCA'].tolist()
        aa = m[0]
        result_pre.append(aa)
    elif  res_ =={'Non_SuspectedCCA', 'SuspectedCCA'}:
        aa = 'SuspectedCCA'
        result_pre.append(aa)
    elif  res_ =={'Normal', 'SuspectedCCA'}:
        aa = 'SuspectedCCA'
        result_pre.append(aa)
    elif  res_ =={'Non_SuspectedCCA', 'Normal'}:
        aa = 'Non_SuspectedCCA'
        result_pre.append(aa)
    elif res_ =={'Non_SuspectedCCA', 'Normal', 'SuspectedCCA'}:
        aa = 'SuspectedCCA'
        result_pre.append(aa)
        
dff2['CCA_Case_AIAct_3'] = result_pre
dff2['Case'] = case

In [149]:
dff2

         Case      CCA_Case_Act       CCA_Case_AI  CCA_Case_AIAct_3
0           1            Normal            Normal            Normal
1    AB081_65      SuspectedCCA      SuspectedCCA      SuspectedCCA
2     AB02_30  Non_SuspectedCCA  Non_SuspectedCCA  Non_SuspectedCCA
3      AB10_9  Non_SuspectedCCA  Non_SuspectedCCA  Non_SuspectedCCA
4     AB02_90  Non_SuspectedCCA  Non_SuspectedCCA  Non_SuspectedCCA
..        ...               ...               ...               ...
368   Ab3_136  Non_SuspectedCCA  Non_SuspectedCCA  Non_SuspectedCCA
369       150            Normal            Normal            Normal
370  AB09_101  Non_SuspectedCCA      SuspectedCCA      SuspectedCCA
371    AB05_2      SuspectedCCA            Normal            Normal
372       141            Normal            Normal            Normal

[373 rows x 4 columns]

In [150]:
a = dff2['CCA_Case_Act'].tolist()
b = dff2['CCA_Case_AI'].tolist()

res =[]
for  i in range(len(a)):
    if a[i] == b[i]:
        res.append('Correct')
    else:
        res.append('Incorrect')
dff2['AI_Pred_CCA']  = res

a = dff2['CCA_Case_Act'].tolist()
b = dff2['CCA_Case_AIAct_3'].tolist()

res =[]
for  i in range(len(a)):
    if a[i] == b[i]:
        res.append('Correct')
    else:
        res.append('Incorrect')
dff2['AI_Pred_CCAAct_3']  = res

#### Recall

In [151]:
#BiTNeT
Correct = dff2[dff2['AI_Pred_CCA'] == 'Correct']
Incorrect = dff2[dff2['AI_Pred_CCA'] == 'Incorrect']
Incorrect[["CCA_Case_Act","CCA_Case_AI" ,"Case"]].groupby(['CCA_Case_Act',"CCA_Case_AI"]).count().reset_index()

       CCA_Case_Act       CCA_Case_AI  Case
0  Non_SuspectedCCA            Normal    21
1  Non_SuspectedCCA      SuspectedCCA     3
2            Normal  Non_SuspectedCCA     2
3            Normal      SuspectedCCA     2
4      SuspectedCCA  Non_SuspectedCCA     6
5      SuspectedCCA            Normal    29

In [152]:
#BiTNeT+FP
Correct = dff2[dff2['AI_Pred_CCAAct_3'] == 'Correct']
Incorrect = dff2[dff2['AI_Pred_CCAAct_3'] == 'Incorrect']
Incorrect[["CCA_Case_Act","CCA_Case_AIAct_3" ,"Case"]].groupby(['CCA_Case_Act',"CCA_Case_AIAct_3"]).count().reset_index()

       CCA_Case_Act  CCA_Case_AIAct_3  Case
0  Non_SuspectedCCA            Normal    21
1  Non_SuspectedCCA      SuspectedCCA     3
2            Normal  Non_SuspectedCCA     1
3            Normal      SuspectedCCA     2
4      SuspectedCCA  Non_SuspectedCCA     4
5      SuspectedCCA            Normal    29

#### Precision

In [153]:
#BiTNeT
dff2[["CCA_Case_AI", "AI_Pred_CCA", "Case"]].groupby(["CCA_Case_AI", "AI_Pred_CCA"]).count().reset_index()

        CCA_Case_AI AI_Pred_CCA  Case
0  Non_SuspectedCCA     Correct   164
1  Non_SuspectedCCA   Incorrect     8
2            Normal     Correct    67
3            Normal   Incorrect    50
4      SuspectedCCA     Correct    79
5      SuspectedCCA   Incorrect     5

In [154]:
#BiTNeT+FP
dff2[["CCA_Case_AI", "AI_Pred_CCAAct_3", "Case"]].groupby(["CCA_Case_AI", "AI_Pred_CCAAct_3"]).count().reset_index()

        CCA_Case_AI AI_Pred_CCAAct_3  Case
0  Non_SuspectedCCA          Correct   167
1  Non_SuspectedCCA        Incorrect     5
2            Normal          Correct    67
3            Normal        Incorrect    50
4      SuspectedCCA          Correct    79
5      SuspectedCCA        Incorrect     5

In [155]:
len(set(dff2[dff2['CCA_Case_Act'] == 'SuspectedCCA']['Case']))

114

In [156]:
len(set(dff2[dff2['CCA_Case_Act'] == 'Normal']['Case']))

71

In [157]:
len(set(dff2[dff2['CCA_Case_Act'] == 'Non_SuspectedCCA']['Case']))

188