In [4]:
import pandas as pd
df = pd.read_csv( '/home/yupaporn/CCA_Project/result_BiTNet_DiagRadioExp_AzureDb813.csv')#แก้
df

,Unnamed: 0,Unnamed: 0.1,0,1,2,3,4,5,6,7,...,P ID,date,Path crop,Class,Sub_class_name,Sub_class,category,Prob,category_BiTNet,Prob_BiTNet
0,0,0,0.070262,0.613967,-0.144178,-0.133302,0.152672,0.177257,-0.094050,-0.097930,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.999987,Normal,0.576555
1,1,1,0.424074,0.373215,-0.190315,-0.057949,-0.046992,0.396701,0.121641,-0.017305,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.942473
2,2,2,0.887827,0.255022,-0.073275,-0.155301,-0.180442,0.398387,-0.110631,0.108062,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.995922,Normal,0.250000
3,3,3,0.124215,0.241486,-0.099518,-0.124972,-0.212320,0.218725,-0.138051,-0.132332,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.999326,Normal,0.465318
4,4,4,-0.029640,0.437044,-0.144407,-0.192584,0.280804,0.065014,-0.090790,-0.185189,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.633762
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
808,808,808,0.494716,0.158680,-0.072473,-0.118034,-0.160107,0.144856,-0.144092,-0.112001,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],AB12,0.998886,AB12,0.232227
809,809,809,0.862474,0.214631,-0.196177,-0.148607,-0.141830,-0.049645,-0.127183,0.034096,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.977855
810,810,810,0.731910,0.300760,-0.141567,-0.141887,0.099090,0.103995,-0.079066,-0.067519,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.987500
811,811,811,0.110222,-0.086056,0.015444,-0.166297,-0.207414,0.202673,-0.124514,-0.214145,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],AB12,0.999583,AB12,0.146717
812,812,812,0.280099,0.234322,-0.189338,-0.174745,-0.208500,0.035469,-0.138305,-0.173777,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.999239,Normal,0.598805

In [5]:
normal = df[df['Class'] == 'Normal']
normal

,Unnamed: 0,Unnamed: 0.1,0,1,2,3,4,5,6,7,...,P ID,date,Path crop,Class,Sub_class_name,Sub_class,category,Prob,category_BiTNet,Prob_BiTNet
0,0,0,0.070262,0.613967,-0.144178,-0.133302,0.152672,0.177257,-0.094050,-0.097930,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.999987,Normal,0.576555
1,1,1,0.424074,0.373215,-0.190315,-0.057949,-0.046992,0.396701,0.121641,-0.017305,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.942473
2,2,2,0.887827,0.255022,-0.073275,-0.155301,-0.180442,0.398387,-0.110631,0.108062,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.995922,Normal,0.250000
3,3,3,0.124215,0.241486,-0.099518,-0.124972,-0.212320,0.218725,-0.138051,-0.132332,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.999326,Normal,0.465318
4,4,4,-0.029640,0.437044,-0.144407,-0.192584,0.280804,0.065014,-0.090790,-0.185189,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.633762
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
808,808,808,0.494716,0.158680,-0.072473,-0.118034,-0.160107,0.144856,-0.144092,-0.112001,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],AB12,0.998886,AB12,0.232227
809,809,809,0.862474,0.214631,-0.196177,-0.148607,-0.141830,-0.049645,-0.127183,0.034096,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.977855
810,810,810,0.731910,0.300760,-0.141567,-0.141887,0.099090,0.103995,-0.079066,-0.067519,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.987500
811,811,811,0.110222,-0.086056,0.015444,-0.166297,-0.207414,0.202673,-0.124514,-0.214145,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],AB12,0.999583,AB12,0.146717
812,812,812,0.280099,0.234322,-0.189338,-0.174745,-0.208500,0.035469,-0.138305,-0.173777,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.999239,Normal,0.598805

In [6]:
abnormal = df[df['Class'] != 'Normal']
abnormal

,Unnamed: 0,Unnamed: 0.1,0,1,2,3,4,5,6,7,...,P ID,date,Path crop,Class,Sub_class_name,Sub_class,category,Prob,category_BiTNet,Prob_BiTNet
100,100,100,0.193559,0.068630,-0.189468,-0.063140,-0.232570,-0.185827,-0.176146,-0.223140,...,6600,20/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Abnormal,['MildFattyLiver'],['AB01'],Normal,0.853607,Normal,0.153379
101,101,101,0.063899,0.283351,-0.161782,0.086769,0.135756,0.134332,-0.012321,-0.149230,...,6600,20/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Abnormal,['MildFattyLiver'],['AB01'],Normal,0.859416,Normal,0.347978
102,102,102,0.057059,0.191134,-0.126757,-0.155400,-0.147156,0.050429,-0.163570,-0.226404,...,6600,20/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Abnormal,['MildFattyLiver'],['AB01'],Normal,0.990697,Normal,0.400161
103,103,103,-0.145865,0.006016,-0.165345,-0.197297,-0.012755,-0.089747,-0.052922,-0.187992,...,6600,20/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Abnormal,['MildFattyLiver'],['AB01'],Normal,0.998711,Normal,0.181747
104,104,104,0.366433,0.094555,0.020924,-0.100951,0.031328,-0.050025,-0.104250,0.180628,...,6600,20/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Abnormal,['MildFattyLiver'],['AB01'],Normal,0.999505,Normal,0.461878
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
721,721,721,0.571876,0.044969,-0.153373,-0.172749,-0.136495,0.020086,-0.125412,-0.195536,...,12279,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Abnormal,['Gallbladderpolyp'],['AB09'],AB12,0.999920,AB12,0.141203
722,722,722,-0.139438,0.317918,-0.177244,-0.052985,-0.192308,-0.168466,-0.151164,-0.014344,...,12279,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Abnormal,['Gallbladderpolyp'],['AB09'],Normal,0.681042,Normal,0.248633
723,723,723,-0.013086,0.515403,-0.119746,-0.175713,-0.196168,-0.045858,-0.013067,-0.106873,...,12279,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Abnormal,['Gallbladderpolyp'],['AB09'],Normal,1.000000,Normal,0.965289
724,724,724,0.425063,-0.026025,-0.090838,-0.177753,-0.196369,-0.042716,-0.139231,-0.159553,...,12279,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Abnormal,['Gallbladderpolyp'],['AB09'],AB12,0.999271,AB12,0.104243
725,725,725,0.740553,0.654441,-0.133752,-0.157047,-0.154843,0.444582,-0.079095,-0.205787,...,12279,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Abnormal,['Gallbladderpolyp'],['AB09'],Normal,0.999773,Normal,0.867282

# Abnomal

In [7]:
class_ = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']

In [8]:
col_name = ['Case', 'Act_label', 'Pred_label','Num_PredCase']
dff2 = pd.DataFrame(columns = col_name)

In [9]:
df_ = abnormal

In [10]:
case = list(set(df_['P ID']))
pred_label = []
num_case = []
act_label = []

for i in case:
    cas_pred = set(df_[df_['P ID'] == i]['category_BiTNet'])
    cas_act = list(df_[df_['P ID'] == i]['Sub_class'])
    pred_label.append(list(cas_pred))
    act_label.append(cas_act[0])
    num_case.append(len(cas_pred))

dff2['Pred_label'] = pred_label
dff2['Case'] = case
dff2['Num_PredCase'] = num_case
dff2['Act_label'] = act_label

In [11]:
dff2

     Case          Act_label                          Pred_label  Num_PredCase
0    6624           ['AB05']                [AB12, AB04, Normal]             3
1   12259           ['AB01']                      [AB12, Normal]             2
2   12261           ['AB02']                      [AB12, Normal]             2
3   12263           ['AB11']                      [AB12, Normal]             2
4    6600           ['AB01']  [AB082, AB081, Normal, AB01, AB12]             5
5    6472  ['AB06', 'AB081']                [AB05, AB12, Normal]             3
6   12264           ['AB01']                [AB01, AB12, Normal]             3
7   12265           ['AB03']          [AB03, AB12, Normal, AB02]             4
8    6668   ['AB02', 'AB11']                      [AB12, Normal]             2
9    7725           ['AB01']                      [AB12, Normal]             2
10   6446           ['AB09']                [AB09, AB12, Normal]             3
11  12221           ['AB01']                      [AB12, Normal]             2
12   6640           ['AB11']                      [AB12, Normal]             2
13  12275           ['AB01']                [AB12, Normal, AB02]             3
14  12222           ['AB02']                      [AB12, Normal]             2
15  12279           ['AB09']                      [AB12, Normal]             2
16   7895           ['AB10']               [AB082, AB12, Normal]             3
17   6621           ['AB01']                      [AB12, Normal]             2
18  12158           ['AB01']                      [AB12, Normal]             2
19   7039           ['AB11']                [AB09, AB12, Normal]             3

In [12]:
#แปลงข้อมูล
Act_label = dff2['Act_label'].tolist()
Act_label_ =[]
for i in Act_label:
    a = i.split("'")
    if len(a) ==5:
        aa = '['+a[1]+','+a[3]+']'
        Act_label_.append(aa)
#         print(aa)
    else:
        aa = '['+a[1]+']'
        Act_label_.append(aa)
#         print(aa)
        
#     print(aa)

In [13]:
Act_label_

['[AB05]',
 '[AB01]',
 '[AB02]',
 '[AB11]',
 '[AB01]',
 '[AB06,AB081]',
 '[AB01]',
 '[AB03]',
 '[AB02,AB11]',
 '[AB01]',
 '[AB09]',
 '[AB01]',
 '[AB11]',
 '[AB01]',
 '[AB02]',
 '[AB09]',
 '[AB10]',
 '[AB01]',
 '[AB01]',
 '[AB11]']

In [14]:
Act_label

["['AB05']",
 "['AB01']",
 "['AB02']",
 "['AB11']",
 "['AB01']",
 "['AB06', 'AB081']",
 "['AB01']",
 "['AB03']",
 "['AB02', 'AB11']",
 "['AB01']",
 "['AB09']",
 "['AB01']",
 "['AB11']",
 "['AB01']",
 "['AB02']",
 "['AB09']",
 "['AB10']",
 "['AB01']",
 "['AB01']",
 "['AB11']"]

# แปลงข้อมูล

In [15]:
import numpy as np

In [16]:
Act_label = dff2['Act_label'].tolist()
Act_label_ =[]
for i in Act_label:   
    a = i.split("'")
    if len(a) ==5:
        m = a[1],a[3]
        g =[]
        for j in range(2):
            g.append(m[j])
        Act_label_.append(g)
    else:
        g =[]
        g.append(a[1])
        Act_label_.append(g)

In [17]:
Act_label_

[['AB05'],
 ['AB01'],
 ['AB02'],
 ['AB11'],
 ['AB01'],
 ['AB06', 'AB081'],
 ['AB01'],
 ['AB03'],
 ['AB02', 'AB11'],
 ['AB01'],
 ['AB09'],
 ['AB01'],
 ['AB11'],
 ['AB01'],
 ['AB02'],
 ['AB09'],
 ['AB10'],
 ['AB01'],
 ['AB01'],
 ['AB11']]

In [18]:
dff2['Act_label_'] = Act_label_

In [19]:
Act = dff2['Act_label_'].tolist()
class_ = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']
# class_ = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12']


cla_act = []
for i in Act:
    if len(list(i)) == 1:
        print(list(i))
        a = str(list(i)[0])
        for j in range(len(class_)):
            if a == class_[j]:
                m = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
                m[j] = 1
                cla_act.append(m)
                print(m)
    else:
        m = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        for j in list(i):
            print(list(i))
            for k in range(len(class_)):
                if j == class_[k]:
                    m[k] = 1
        cla_act.append(m)
        print(m)

['AB05']
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['AB01']
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['AB02']
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['AB11']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
['AB01']
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['AB06', 'AB081']
['AB06', 'AB081']
[0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0]
['AB01']
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['AB03']
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['AB02', 'AB11']
['AB02', 'AB11']
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
['AB01']
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['AB09']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
['AB01']
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['AB11']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
['AB01']
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['AB02']
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['AB09']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
['AB10']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
['AB01']
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['AB01']
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['AB11']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]

In [20]:
cla_act

[[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]]

In [21]:
a =[]
for i in cla_act:
    a.append(i[0:14])
#     print(i[0:14])
cla_act_ = a

In [22]:
cla_act_

[[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]]

In [23]:
print(len(cla_act_))

20

In [24]:
print(len(Act))

20

In [25]:
Act

[['AB05'],
 ['AB01'],
 ['AB02'],
 ['AB11'],
 ['AB01'],
 ['AB06', 'AB081'],
 ['AB01'],
 ['AB03'],
 ['AB02', 'AB11'],
 ['AB01'],
 ['AB09'],
 ['AB01'],
 ['AB11'],
 ['AB01'],
 ['AB02'],
 ['AB09'],
 ['AB10'],
 ['AB01'],
 ['AB01'],
 ['AB11']]

In [26]:
Pred = dff2['Pred_label'].tolist()
class_ = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']

cla_pred = []
for i in Pred:
    if len(list(i)) == 1:
        a = str(list(i)[0])
        for j in range(len(class_)):
            if a == class_[j]:
                m = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
                m[j] = 1
                cla_pred.append(m)
    else:
        m = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        for j in list(i):
            print(list(i))
            for k in range(len(class_)):
                if j == class_[k]:
                    m[k] = 1
        cla_pred.append(m)
        print(m)

['AB12', 'AB04', 'Normal']
['AB12', 'AB04', 'Normal']
['AB12', 'AB04', 'Normal']
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB082', 'AB081', 'Normal', 'AB01', 'AB12']
['AB082', 'AB081', 'Normal', 'AB01', 'AB12']
['AB082', 'AB081', 'Normal', 'AB01', 'AB12']
['AB082', 'AB081', 'Normal', 'AB01', 'AB12']
['AB082', 'AB081', 'Normal', 'AB01', 'AB12']
[1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1]
['AB05', 'AB12', 'Normal']
['AB05', 'AB12', 'Normal']
['AB05', 'AB12', 'Normal']
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB01', 'AB12', 'Normal']
['AB01', 'AB12', 'Normal']
['AB01', 'AB12', 'Normal']
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB03', 'AB12', 'Normal', 'AB02']
['AB03', 'AB12', 'Normal', 'AB02']
['AB03', 'AB12', 'Normal', 'AB02']
['AB03', 'AB12', 'Normal', 'AB02']
[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB09', 'AB12', 'Normal']
['AB09', 'AB12', 'Normal']
['AB09', 'AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal', 'AB02']
['AB12', 'Normal', 'AB02']
['AB12', 'Normal', 'AB02']
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB082', 'AB12', 'Normal']
['AB082', 'AB12', 'Normal']
['AB082', 'AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB09', 'AB12', 'Normal']
['AB09', 'AB12', 'Normal']
['AB09', 'AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1]

In [27]:
a =[]
for i in cla_pred:
    a.append(i[0:14])
#     print(i[0:14])
cla_pred_ = a

In [28]:
cla_pred

[[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1]]

In [29]:
cla_pred_

[[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]]

In [30]:
dff2['Act'] = cla_act_
dff2['Pred'] = cla_pred_

In [31]:
dff2

,Case,Act_label,Pred_label,Num_PredCase,Act_label_,Act,Pred
0,6624,['AB05'],"[AB12, AB04, Normal]",3,[AB05],"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
1,12259,['AB01'],"[AB12, Normal]",2,[AB01],"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
2,12261,['AB02'],"[AB12, Normal]",2,[AB02],"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
3,12263,['AB11'],"[AB12, Normal]",2,[AB11],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
4,6600,['AB01'],"[AB082, AB081, Normal, AB01, AB12]",5,[AB01],"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1]"
5,6472,"['AB06', 'AB081']","[AB05, AB12, Normal]",3,"[AB06, AB081]","[0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
6,12264,['AB01'],"[AB01, AB12, Normal]",3,[AB01],"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
7,12265,['AB03'],"[AB03, AB12, Normal, AB02]",4,[AB03],"[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
8,6668,"['AB02', 'AB11']","[AB12, Normal]",2,"[AB02, AB11]","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
9,7725,['AB01'],"[AB12, Normal]",2,[AB01],"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
10,6446,['AB09'],"[AB09, AB12, Normal]",3,[AB09],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]"
11,12221,['AB01'],"[AB12, Normal]",2,[AB01],"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
12,6640,['AB11'],"[AB12, Normal]",2,[AB11],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
13,12275,['AB01'],"[AB12, Normal, AB02]",3,[AB01],"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
14,12222,['AB02'],"[AB12, Normal]",2,[AB02],"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
15,12279,['AB09'],"[AB12, Normal]",2,[AB09],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
16,7895,['AB10'],"[AB082, AB12, Normal]",3,[AB10],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]"
17,6621,['AB01'],"[AB12, Normal]",2,[AB01],"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
18,12158,['AB01'],"[AB12, Normal]",2,[AB01],"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
19,7039,['AB11'],"[AB09, AB12, Normal]",3,[AB11],"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]"

# Evaluation

In [32]:
import numpy as np
y_true = np.array(cla_act_)
y_pred = np.array(cla_pred_)

In [33]:
from sklearn.metrics import accuracy_score
accuracy_score(y_true, y_pred)

0.0

In [34]:
from sklearn.metrics import multilabel_confusion_matrix
multilabel_confusion_matrix(y_true, y_pred)

array([[[12,  0],
        [ 6,  2]],

       [[15,  2],
        [ 3,  0]],

       [[19,  0],
        [ 0,  1]],

       [[19,  1],
        [ 0,  0]],

       [[18,  1],
        [ 1,  0]],

       [[19,  0],
        [ 1,  0]],

       [[20,  0],
        [ 0,  0]],

       [[18,  1],
        [ 1,  0]],

       [[18,  2],
        [ 0,  0]],

       [[20,  0],
        [ 0,  0]],

       [[17,  1],
        [ 1,  1]],

       [[19,  0],
        [ 1,  0]],

       [[16,  0],
        [ 4,  0]],

       [[ 0, 20],
        [ 0,  0]]])

In [35]:
from sklearn.metrics import classification_report

# label_names = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']
label_names = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12']

print(classification_report(y_true, y_pred,target_names=label_names))

              precision    recall  f1-score   support

        AB01       1.00      0.25      0.40         8
        AB02       0.00      0.00      0.00         3
        AB03       1.00      1.00      1.00         1
        AB04       0.00      0.00      0.00         0
        AB05       0.00      0.00      0.00         1
        AB06       0.00      0.00      0.00         1
        AB07       0.00      0.00      0.00         0
       AB081       0.00      0.00      0.00         1
       AB082       0.00      0.00      0.00         0
       AB083       0.00      0.00      0.00         0
        AB09       0.50      0.50      0.50         2
        AB10       0.00      0.00      0.00         1
        AB11       0.00      0.00      0.00         4
        AB12       0.00      0.00      0.00         0

   micro avg       0.12      0.18      0.15        22
   macro avg       0.18      0.12      0.14        22
weighted avg       0.45      0.18      0.24        22
 samples avg       0.08      0.20      0.11        22

/home/yupaporn/miniconda3/envs/USAI3/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/yupaporn/miniconda3/envs/USAI3/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

# Normal

In [122]:
normal = df[df['Class'] == 'Normal']
normal

,Unnamed: 0,Unnamed: 0.1,0,1,2,3,4,5,6,7,...,P ID,date,Path crop,Class,Sub_class_name,Sub_class,category,Prob,category_BiTNet,Prob_BiTNet
0,0,0,0.070262,0.613967,-0.144178,-0.133302,0.152672,0.177257,-0.094050,-0.097930,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.999987,Normal,0.576555
1,1,1,0.424074,0.373215,-0.190315,-0.057949,-0.046992,0.396701,0.121641,-0.017305,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.942473
2,2,2,0.887827,0.255022,-0.073275,-0.155301,-0.180442,0.398387,-0.110631,0.108062,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.995922,Normal,0.250000
3,3,3,0.124215,0.241486,-0.099518,-0.124972,-0.212320,0.218725,-0.138051,-0.132332,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.999326,Normal,0.465318
4,4,4,-0.029640,0.437044,-0.144407,-0.192584,0.280804,0.065014,-0.090790,-0.185189,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.633762
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
808,808,808,0.494716,0.158680,-0.072473,-0.118034,-0.160107,0.144856,-0.144092,-0.112001,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],AB12,0.998886,AB12,0.232227
809,809,809,0.862474,0.214631,-0.196177,-0.148607,-0.141830,-0.049645,-0.127183,0.034096,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.977855
810,810,810,0.731910,0.300760,-0.141567,-0.141887,0.099090,0.103995,-0.079066,-0.067519,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.987500
811,811,811,0.110222,-0.086056,0.015444,-0.166297,-0.207414,0.202673,-0.124514,-0.214145,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],AB12,0.999583,AB12,0.146717
812,812,812,0.280099,0.234322,-0.189338,-0.174745,-0.208500,0.035469,-0.138305,-0.173777,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.999239,Normal,0.598805

In [123]:
class_ = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']
col_name = ['Case', 'Act_label', 'Pred_label','Num_PredCase']
dff2 = pd.DataFrame(columns = col_name)

df_ = normal

case = list(set(df_['P ID']))
pred_label = []
num_case = []
act_label = []

for i in case:
    cas_pred = set(df_[df_['P ID'] == i]['category_BiTNet'])
    cas_act = list(df_[df_['P ID'] == i]['Sub_class'])
    pred_label.append(list(cas_pred))
    act_label.append(cas_act[0])
    num_case.append(len(cas_pred))

dff2['Pred_label'] = pred_label
dff2['Case'] = case
dff2['Num_PredCase'] = num_case
dff2['Act_label'] = act_label

In [124]:
dff2

     Case   Act_label                   Pred_label  Num_PredCase
0    6798  ['Normal']               [AB12, Normal]             2
1   12215  ['Normal']               [AB12, Normal]             2
2   12216  ['Normal']         [AB12, Normal, AB04]             3
3   12217  ['Normal']               [AB01, Normal]             2
4   12218  ['Normal']               [AB12, Normal]             2
5   12219  ['Normal']               [AB12, Normal]             2
6   12220  ['Normal']               [AB12, Normal]             2
7   12248  ['Normal']         [AB05, AB12, Normal]             3
8   12280  ['Normal']               [AB12, Normal]             2
9   12282  ['Normal']               [AB12, Normal]             2
10  12260  ['Normal']         [AB07, AB12, Normal]             3
11  12262  ['Normal']               [AB12, Normal]             2
12  12283  ['Normal']                     [Normal]             1
13  12266  ['Normal']               [AB12, Normal]             2
14  12284  ['Normal']                     [Normal]             1
15  12269  ['Normal']                     [Normal]             1
16  12270  ['Normal']               [AB12, Normal]             2
17  12271  ['Normal']               [AB12, Normal]             2
18  12273  ['Normal']               [AB12, Normal]             2
19  12274  ['Normal']               [AB12, Normal]             2
20  12285  ['Normal']               [AB12, Normal]             2
21  12276  ['Normal']        [AB081, Normal, AB12]             3
22  12277  ['Normal']        [AB082, AB12, Normal]             3
23  12150  ['Normal']                     [Normal]             1
24  12151  ['Normal']               [AB12, Normal]             2
25  12152  ['Normal']               [AB12, Normal]             2
26  12281  ['Normal']  [AB05, AB081, Normal, AB12]             4
27  12154  ['Normal']               [AB12, Normal]             2
28  12155  ['Normal']              [AB081, Normal]             2
29  12156  ['Normal']               [AB12, Normal]             2
30   6525  ['Normal']               [AB12, Normal]             2

In [131]:
Act = dff2['Act_label'].tolist()
cla_act = []
for i in Act:
    m = [1,0]
    cla_act.append(m)

In [130]:
Act = dff2['Pred_label'].tolist()
cla_pred = []
for i in Pred:
    if len(list(i)) == 1:
        if i == ['Normal']:
            a =[1,0]
            cla_pred.append(a)
        else:
            a =[0,1]
            cla_pred.append(a)
    else:
        a =[0,1]
        cla_pred.append(a)

In [135]:
import numpy as np
y_true = np.array(cla_act)
y_pred = np.array(cla_pred)

from sklearn.metrics import accuracy_score
accuracy_score(y_true, y_pred)

0.12903225806451613

In [136]:
from sklearn.metrics import multilabel_confusion_matrix
# multilabel_confusion_matrix(y_true, y_pred)

from sklearn.metrics import classification_report

label_names = ['Normal', 'Abnormal']
print(classification_report(y_true, y_pred,target_names=label_names))

              precision    recall  f1-score   support

      Normal       1.00      0.13      0.23        31
    Abnormal       0.00      0.00      0.00         0

   micro avg       0.13      0.13      0.13        31
   macro avg       0.50      0.06      0.11        31
weighted avg       1.00      0.13      0.23        31
 samples avg       0.13      0.13      0.13        31

/home/yupaporn/miniconda3/envs/USAI3/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

## วิธีที่ 2

In [97]:
normal = df[df['Class'] == 'Normal']
normal

,Unnamed: 0,Unnamed: 0.1,0,1,2,3,4,5,6,7,...,P ID,date,Path crop,Class,Sub_class_name,Sub_class,category,Prob,category_BiTNet,Prob_BiTNet
0,0,0,0.070262,0.613967,-0.144178,-0.133302,0.152672,0.177257,-0.094050,-0.097930,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.999987,Normal,0.576555
1,1,1,0.424074,0.373215,-0.190315,-0.057949,-0.046992,0.396701,0.121641,-0.017305,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.942473
2,2,2,0.887827,0.255022,-0.073275,-0.155301,-0.180442,0.398387,-0.110631,0.108062,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.995922,Normal,0.250000
3,3,3,0.124215,0.241486,-0.099518,-0.124972,-0.212320,0.218725,-0.138051,-0.132332,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.999326,Normal,0.465318
4,4,4,-0.029640,0.437044,-0.144407,-0.192584,0.280804,0.065014,-0.090790,-0.185189,...,12150,11/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.633762
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
808,808,808,0.494716,0.158680,-0.072473,-0.118034,-0.160107,0.144856,-0.144092,-0.112001,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],AB12,0.998886,AB12,0.232227
809,809,809,0.862474,0.214631,-0.196177,-0.148607,-0.141830,-0.049645,-0.127183,0.034096,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.977855
810,810,810,0.731910,0.300760,-0.141567,-0.141887,0.099090,0.103995,-0.079066,-0.067519,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,1.000000,Normal,0.987500
811,811,811,0.110222,-0.086056,0.015444,-0.166297,-0.207414,0.202673,-0.124514,-0.214145,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],AB12,0.999583,AB12,0.146717
812,812,812,0.280099,0.234322,-0.189338,-0.174745,-0.208500,0.035469,-0.138305,-0.173777,...,12285,27/10/2021,/media/tohn/SSD/ImageFromAzureDB_IsanCohort_cr...,Normal,['Normal'],['Normal'],Normal,0.999239,Normal,0.598805

In [98]:
class_ = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']
col_name = ['Case', 'Act_label', 'Pred_label','Num_PredCase']
dff2 = pd.DataFrame(columns = col_name)

In [99]:
df_ = normal

In [100]:
case = list(set(df_['P ID']))
pred_label = []
num_case = []
act_label = []

In [101]:
for i in case:
    cas_pred = set(df_[df_['P ID'] == i]['category_BiTNet'])
    cas_act = list(df_[df_['P ID'] == i]['Sub_class'])
    pred_label.append(list(cas_pred))
    act_label.append(cas_act[0])
    num_case.append(len(cas_pred))

dff2['Pred_label'] = pred_label
dff2['Case'] = case
dff2['Num_PredCase'] = num_case
dff2['Act_label'] = act_label

In [102]:
dff2

     Case   Act_label                   Pred_label  Num_PredCase
0    6798  ['Normal']               [AB12, Normal]             2
1   12215  ['Normal']               [AB12, Normal]             2
2   12216  ['Normal']         [AB12, Normal, AB04]             3
3   12217  ['Normal']               [AB01, Normal]             2
4   12218  ['Normal']               [AB12, Normal]             2
5   12219  ['Normal']               [AB12, Normal]             2
6   12220  ['Normal']               [AB12, Normal]             2
7   12248  ['Normal']         [AB05, AB12, Normal]             3
8   12280  ['Normal']               [AB12, Normal]             2
9   12282  ['Normal']               [AB12, Normal]             2
10  12260  ['Normal']         [AB07, AB12, Normal]             3
11  12262  ['Normal']               [AB12, Normal]             2
12  12283  ['Normal']                     [Normal]             1
13  12266  ['Normal']               [AB12, Normal]             2
14  12284  ['Normal']                     [Normal]             1
15  12269  ['Normal']                     [Normal]             1
16  12270  ['Normal']               [AB12, Normal]             2
17  12271  ['Normal']               [AB12, Normal]             2
18  12273  ['Normal']               [AB12, Normal]             2
19  12274  ['Normal']               [AB12, Normal]             2
20  12285  ['Normal']               [AB12, Normal]             2
21  12276  ['Normal']        [AB081, Normal, AB12]             3
22  12277  ['Normal']        [AB082, AB12, Normal]             3
23  12150  ['Normal']                     [Normal]             1
24  12151  ['Normal']               [AB12, Normal]             2
25  12152  ['Normal']               [AB12, Normal]             2
26  12281  ['Normal']  [AB05, AB081, Normal, AB12]             4
27  12154  ['Normal']               [AB12, Normal]             2
28  12155  ['Normal']              [AB081, Normal]             2
29  12156  ['Normal']               [AB12, Normal]             2
30   6525  ['Normal']               [AB12, Normal]             2

In [114]:
Act = dff2['Act_label'].tolist()
cla_act = []
for i in Act:
    m = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
    cla_act.append(m)

In [106]:
Pred = dff2['Pred_label'].tolist()
class_ = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']

cla_pred = []
for i in Pred:
    if len(list(i)) == 1:
        a = str(list(i)[0])
        for j in range(len(class_)):
            if a == class_[j]:
                m = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
                m[j] = 1
                cla_pred.append(m)
    else:
        m = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        for j in list(i):
            print(list(i))
            for k in range(len(class_)):
                if j == class_[k]:
                    m[k] = 1
        cla_pred.append(m)
        print(m)

['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal', 'AB04']
['AB12', 'Normal', 'AB04']
['AB12', 'Normal', 'AB04']
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB01', 'Normal']
['AB01', 'Normal']
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB05', 'AB12', 'Normal']
['AB05', 'AB12', 'Normal']
['AB05', 'AB12', 'Normal']
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB07', 'AB12', 'Normal']
['AB07', 'AB12', 'Normal']
['AB07', 'AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB081', 'Normal', 'AB12']
['AB081', 'Normal', 'AB12']
['AB081', 'Normal', 'AB12']
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1]
['AB082', 'AB12', 'Normal']
['AB082', 'AB12', 'Normal']
['AB082', 'AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB05', 'AB081', 'Normal', 'AB12']
['AB05', 'AB081', 'Normal', 'AB12']
['AB05', 'AB081', 'Normal', 'AB12']
['AB05', 'AB081', 'Normal', 'AB12']
[0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB081', 'Normal']
['AB081', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
['AB12', 'Normal']
['AB12', 'Normal']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]

In [121]:
dff2['Act'] = cla_act
dff2['Pred'] = cla_pred
dff2

,Case,Act_label,Pred_label,Num_PredCase,Act,Pred
0,6798,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
1,12215,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
2,12216,['Normal'],"[AB12, Normal, AB04]",3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
3,12217,['Normal'],"[AB01, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
4,12218,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
5,12219,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
6,12220,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
7,12248,['Normal'],"[AB05, AB12, Normal]",3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
8,12280,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
9,12282,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
10,12260,['Normal'],"[AB07, AB12, Normal]",3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1]"
11,12262,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
12,12283,['Normal'],[Normal],1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
13,12266,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
14,12284,['Normal'],[Normal],1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
15,12269,['Normal'],[Normal],1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
16,12270,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
17,12271,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
18,12273,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
19,12274,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
20,12285,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
21,12276,['Normal'],"[AB081, Normal, AB12]",3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1]"
22,12277,['Normal'],"[AB082, AB12, Normal]",3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1]"
23,12150,['Normal'],[Normal],1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"
24,12151,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
25,12152,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
26,12281,['Normal'],"[AB05, AB081, Normal, AB12]",4,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1]"
27,12154,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
28,12155,['Normal'],"[AB081, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1]"
29,12156,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"
30,6525,['Normal'],"[AB12, Normal]",2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]"

In [116]:
import numpy as np
y_true = np.array(cla_act)
y_pred = np.array(cla_pred)

In [117]:
from sklearn.metrics import accuracy_score
accuracy_score(y_true, y_pred)

0.12903225806451613

In [118]:
from sklearn.metrics import multilabel_confusion_matrix
multilabel_confusion_matrix(y_true, y_pred)

array([[[30,  1],
        [ 0,  0]],

       [[31,  0],
        [ 0,  0]],

       [[31,  0],
        [ 0,  0]],

       [[30,  1],
        [ 0,  0]],

       [[29,  2],
        [ 0,  0]],

       [[31,  0],
        [ 0,  0]],

       [[30,  1],
        [ 0,  0]],

       [[28,  3],
        [ 0,  0]],

       [[30,  1],
        [ 0,  0]],

       [[31,  0],
        [ 0,  0]],

       [[31,  0],
        [ 0,  0]],

       [[31,  0],
        [ 0,  0]],

       [[31,  0],
        [ 0,  0]],

       [[ 6, 25],
        [ 0,  0]],

       [[ 0,  0],
        [ 0, 31]]])

In [119]:
from sklearn.metrics import classification_report

label_names = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']
# label_names = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12']

print(classification_report(y_true, y_pred,target_names=label_names))

              precision    recall  f1-score   support

        AB01       0.00      0.00      0.00         0
        AB02       0.00      0.00      0.00         0
        AB03       0.00      0.00      0.00         0
        AB04       0.00      0.00      0.00         0
        AB05       0.00      0.00      0.00         0
        AB06       0.00      0.00      0.00         0
        AB07       0.00      0.00      0.00         0
       AB081       0.00      0.00      0.00         0
       AB082       0.00      0.00      0.00         0
       AB083       0.00      0.00      0.00         0
        AB09       0.00      0.00      0.00         0
        AB10       0.00      0.00      0.00         0
        AB11       0.00      0.00      0.00         0
        AB12       0.00      0.00      0.00         0
      Normal       1.00      1.00      1.00        31

   micro avg       0.48      1.00      0.65        31
   macro avg       0.07      0.07      0.07        31
weighted avg       1.00      1.00      1.00        31
 samples avg       0.53      1.00      0.67        31

/home/yupaporn/miniconda3/envs/USAI3/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/yupaporn/miniconda3/envs/USAI3/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))